### ISSUE TITLE
How do i use Profile Accents?

### ISSUE THREAD

**Issue by fard83** [riolubruh/YABDP4Nitro#104]
I go to the settings in bd and click miscellaneous, nothing pops up, go to profiles, cant use it, I am so confused.

**Comment by riolubruh** [comment]
Make sure [ZeresPluginLibrary](https://betterdiscord.app/plugin/ZeresPluginLibrary) is installed and up to date!

**Comment by fard83** [comment]
> Make sure [ZeresPluginLibrary](https://betterdiscord.app/plugin/ZeresPluginLibrary) is installed and up to date!

it is

**Comment by riolubruh** [comment]
It's a ZeresPluginLibrary bug. Either download the [latest version of ZPL from the GitHub page](https://raw.githubusercontent.com/rauenzi/BDPluginLibrary/master/release/0PluginLibrary.plugin.js) (which is not the same version as the one on the BetterDiscord website) or wait for ZPL 2.0.17 to be released on the BD website.

**Comment by riolubruh** [comment]
Update: the 2.0.17 version of ZPL has been put on the BetterDiscord website. Update to the 2.0.17 version of ZeresPluginLibrary.
