### ISSUE TITLE
Cannot send a sticker with text included; sending an animated sticker wouldn't work with static freeze image results; and feature request to add a sticker to be automatically sized as Discord user Nitro sends an emote.

### ISSUE THREAD

**Issue by ryukora** [riolubruh/YABDP4Nitro#110]
I cannot send stickers with text included, but sending stickers without text is fine; maybe you can consider it a fix or an added feature. 

Example of trying to send a sticker with a text:
![Xhr5M2k82p](https://github.com/riolubruh/YABDP4Nitro/assets/30078972/45555877-ff74-44dc-ae51-dc3d312ce192)

Results:
![aXgrfs4LdJ](https://github.com/riolubruh/YABDP4Nitro/assets/30078972/74a14be5-0a28-41b1-b323-b2c4b07999e3)

But sending a sticker without a text:
![D1myyuftfR](https://github.com/riolubruh/YABDP4Nitro/assets/30078972/ec480b02-9cea-445f-9aa4-539e06b42a5e)

Results (automatically sends an image with a link):
![bqV8X0B4EH](https://github.com/riolubruh/YABDP4Nitro/assets/30078972/eb199d21-56f4-4271-9697-441cb03e2c6b)

Maybe you could add a feature where posting a sticker automatically sizes it to a standard emote-size image, like when a Discord Nitro user sends an emote, their size is different compared to media discord sizes.

**Comment by nxzlem** [comment]
I noticed some problems: sending a sticker with an animated png or gif wouldn't move anything. Maybe another fix?

The animated sticker I'm trying to send:
![send1](https://p.ihateani.me/dejdzpse.gif)

This is what it looks like:
![results1](https://p.ihateani.me/podttmyl.gif)

This shouldn't look like this:
![BbxVWuKQ0U](https://github-production-user-asset-6210df.s3.amazonaws.com/30078972/248908902-fe9af1db-5c7b-4605-b1b8-4da20efbf13c.png)

Modifying the animated sticker in other formats wouldn't also work.
![4vLPastj2m](https://github.com/riolubruh/YABDP4Nitro/assets/30078972/c60439e1-ef03-4e65-ad0f-a83ba76df4f3)

**Comment by riolubruh** [comment]
These issues has been known about for a long time. Unfortunately, I personally couldn't figure out how to convert from APNG (discord's preferred animated sticker format) to GIF (like how FreeStickers does) and then upload the gif as a file. Additionally, being unable to send stickers with added text is a result of:
a) never actually writing code to account for that situation
b) me being too lazy to actually write said code, because most people don't even use the text included with a sticker anyway
and c) me not knowing which function is used for that specific purpose

As for the feature request regarding sizing the sticker, that's another thing that would likely be quite complicated to implement since that would possibly require _upscaling_ the APNG/GIF to be the proper size.

In my research, FreeStickers converts APNG to GIF using _WebAssembly_, which is a big problem cause I don't even know where to start with that :/

**Comment by nxzlem** [comment]
> These issues has been known about for a long time. Unfortunately, I personally couldn't figure out how to convert from APNG (discord's preferred animated sticker format) to GIF (like how FreeStickers does) and then upload the gif as a file. Additionally, being unable to send stickers with added text is a result of: a) never actually writing code to account for that situation b) me being too lazy to actually write said code, because most people don't even use the text included with a sticker anyway and c) me not knowing which function is used for that specific purpose
> 
> As for the feature request regarding sizing the sticker, that's another thing that would likely be quite complicated to implement since that would possibly require _upscaling_ the APNG/GIF to be the proper size.
> 
> In my searching for a way to do all this stuff, I found that FreeStickers converts APNGs to GIFs using _WebAssembly_, which is a big problem cause I don't even know where to start with that :/

Ah, I see. Maybe something new would be a new project if this were a new plan. If you consider it trying as best you can, I hope you can do it!

I apologize if I did something wrong, so I'm very sorry if you cannot do anything.

**Comment by riolubruh** [comment]
No worries! Not all hope is lost; since the last time I tried to implement this I have totally reworked the uploading system, so I'll give it another go!

**Comment by nxzlem** [comment]
> implement this I have totally reworked the uploading system, so I'll give it another go!

Thank you! I hope you can do as much as you can. I wish you all the best in creating a new project!

**Comment by riolubruh** [comment]
Nothing I was trying was working at first, so I took a different approach at this. I started trying to modify FreeStickers itself to fix it, but wasn't getting anywhere. That was when I noticed that there was [already a pull request to FreeStickers](https://github.com/An00nymushun/DiscordFreeStickers/pull/33) that already did most of the work for me... bruh -_- ...
Well anyways here's a version of FreeStickers that works pretty well, with a few minor changes by me, as well as the pull requests from [Et3rnos](https://github.com/Et3rnos) and [ArjhanToteck](https://github.com/ArjhanToteck) added on.
[FreeStickers.plugin.zip](https://github.com/riolubruh/YABDP4Nitro/files/12033070/FreeStickers.plugin.zip)

**Comment by riolubruh** [comment]
I decided to take out [ArjhanToteck](https://github.com/ArjhanToteck)'s fix to the uploader system (that used the message attachment manager) and instead use the exact same uploading code used in YABDP4Nitro.
See https://github.com/riolubruh/DiscordFreeStickers
