### ISSUE TITLE
profile accents

### ISSUE THREAD

**Issue by speedlorenzo12** [riolubruh/YABDP4Nitro#115]
I know that it is not possible to change the profile accents but I know some plugins that use 3y3 to do it and then render it on the profile, is it possible to do it through this do you think?

**Comment by riolubruh** [comment]
It should be possible, I've considered doing it before but I'll have to better learn how 3y3 encoding actually works first

**Comment by riolubruh** [comment]
Here's the progress on this feature so far:
- [ ] Encoding to 3y3
- [ ] "Copy 3y3" button (or an equivalent system)
- [x] Decoding 3y3 colors
- [x] Applying decoded 3y3 colors

**Comment by speedlorenzo12** [comment]
ok great, you are the first one to have made a plugin for betterdiscord that does this bypasser (I was inspired by vencord and vendetta)

**Comment by riolubruh** [comment]
Coming to an update near you
![Discord_K1XU1lQ2Aj](https://github.com/riolubruh/YABDP4Nitro/assets/54255074/55385e86-e5dd-4da9-b21a-c09fdfd301c4)

**Comment by speedlorenzo12** [comment]
👍

**Comment by riolubruh** [comment]
I also tested it, just to be absolutely sure, and it is also confirmed to be working correctly with 3y3s that are copied/generated from Vencord's FakeProfileThemes
![image](https://github.com/riolubruh/YABDP4Nitro/assets/54255074/524682a9-64cd-433a-8004-1dd955073fb9)
