### ISSUE TITLE
"Client sided streaming"

### ISSUE THREAD

**Issue by Serfeather** [riolubruh/YABDP4Nitro#116]
Wouldnt this mean that the streaming quality is for you only?

**Comment by riolubruh** [comment]
> Wouldnt this mean that the streaming quality is for you only?

No. If you test it with two separate clients, there is a noticeable difference in framerate and quality between 720p 30fps (which is the normal limit) and custom streaming quality settings (for example Source 144fps). The opposite also applies; you can set the FPS to 1 and the resolution to 144p and it will appear that way for other users.
That is to say, the stream _quality_ is not client sided. The plugin itself technically does not interact with the API to do this, however; what it does is it unlocks and modifies the buttons that allow you to change the FPS and resolution and also changes the stream quality settings by patching the webpack modules which handle streaming. Of course, how good your stream looks still depends on several factors, such as network speed, how good your computer is, etc., which is also true for Nitro users.
