### ISSUE TITLE
[BUG] When using change Windows Feature Sound doesn't work anymore

### ISSUE THREAD

**Issue by K3NOXOFFICIAL** [riolubruh/YABDP4Nitro#119]
Issue Description:
@riolubruh @spinfal Hey there, I've been using the Discord Nitro plugin's streaming feature for a while now, and I've run into a pretty frustrating problem. Whenever I switch windows while I'm in the middle of streaming, the sound just stops working.

Steps to Reproduce:

I installed and set up the Discord Nitro plugin on my system.
I started a stream.
During the stream, I switched to another application or window.
Then I noticed that the sound had completely of the stream doesn't Work anymore.

Expected Behavior:
I thought that when I switch windows during a streaming session using the Discord Nitro plugin, the sound would just keep working.
I should be able to easily switch between different applications without the stream sound not working anymore

**Comment by riolubruh** [comment]
I don't know if this is even the plugin's fault... it doesn't interact with the sound sharing code **at all**. Have you tried it with a clean Discord/BD install with no plugins? If the problem doesn't occur on a clean Discord install, then it could even be a fault of the program that you are trying to audio share. Some programs don't always work with Discord's audio sharing.

**Comment by K3NOXOFFICIAL** [comment]
@riolubruh  It occurs on all my friends PCs as well and some of them only have this plugin installed, I tried it on 3 PCs myself and I got 5 people who are saying the same thing. It seems to work when turning the plugin off but then only in 720p and that's annoying.

**Comment by riolubruh** [comment]
Thank you for providing the error log. I'll investigate this issue since it seems to be a fairly simple problem: the error is thrown because a variable that the Discord devs set as read-only is directly modified in the plugin, so to combat that all that would have to be done is to delete the object and re-create it without the read-only flag.

**Comment by riolubruh** [comment]
After doing some investigating, I've discovered that if I switch to Discord PTB or Canary, problems similar to this start to occur in several places, which is very concerning.

For example, on Discord PTB, the following code raises the error shown on the right:
![image](https://github.com/riolubruh/YABDP4Nitro/assets/54255074/0a2c52a7-e803-4f3c-a53c-1e18bceb8280)

However, ignoring that disturbing revelation, I have attempted to write a fix to the error which should be in the upcoming update.

**Comment by riolubruh** [comment]
Let me know if 4.6.1 resolved the issue.

**Comment by riolubruh** [comment]
I still have been unable to reproduce the issue. I've been testing it using [mpv](https://mpv.io/), and tested listening to the stream on both a vanilla Google Chrome client and with a second instance of BetterDiscord (using the same plugins) but the problem does not occur on either unless the application is _minimized_ (which is intended vanilla Discord behavior).
IDK what to tell you.

**Comment by K3NOXOFFICIAL** [comment]
@riolubruh Can confirm tho that the issue still persists on all my and my friends devices that have BD with YABDP4Nitro.
Will investigate the issue further today with a few friends and update you if I find smth of interest regarding this issue.

**Comment by greenteabots** [comment]
Can also confirm i have same problem!
