### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by mikejack99** [riolubruh/YABDP4Nitro#12]
I cant  chose the resolutions anymore :( 

Any solution?

**Comment by riolubruh** [comment]
If you're getting something like this:
![image](https://user-images.githubusercontent.com/54255074/177019342-5a0c1a7b-f9b7-4ac6-be57-d390e2d4d843.png)
then it means that you have changed the options of the resolution while you had your previous options selected.
The easiest way to fix this is to just hit the dropdown and choose "Smoother Video".
![image](https://user-images.githubusercontent.com/54255074/177019366-0e423938-2aee-407e-a34e-c8b4c263b2a3.png)
This will restore your options back to this and you will be able to choose whatever you want again.
![image](https://user-images.githubusercontent.com/54255074/177019380-556a0668-f96c-4e92-b02a-4f787c748780.png)

I could make it so this does not happen in the code but it should not be necessary.
If this isn't your issue, then please provide further details. thx

**Comment by mikejack99** [comment]
This solve my problem! Thanks <3

**Comment by 01M** [comment]
Thanks a lot!
