### ISSUE TITLE
??????????/

### ISSUE THREAD

**Issue by Flodsire** [riolubruh/YABDP4Nitro#121]
how tf do you get this on better discord

**Comment by speedlorenzo12** [comment]
Download the plugin and put it in the betterdiscord plugin folder then I don't know what you mean

**Comment by speedlorenzo12** [comment]
Download the plugin and put it in the betterdiscord plugin folder then I don't know what you mean

**Comment by riolubruh** [comment]
Download the plugin file [here](https://github.com/riolubruh/YABDP4Nitro/blob/main/YABDP4Nitro.plugin.js), then put the file in the BetterDiscord plugins folder. If you don't know how to do that, please read the [BetterDiscord documentation on this exact subject](https://docs.betterdiscord.app/users/guides/installing-addons).
