### ISSUE TITLE
the plugin stops working???

### ISSUE THREAD

**Issue by speedlorenzo12** [riolubruh/YABDP4Nitro#122]
probably discord have updated now (stable)

**Comment by riolubruh** [comment]
Yep... looks like the Discord devs froze basically all of the objects in the "permissions" module.

**Comment by riolubruh** [comment]
Current Progress on fixes (replacement functions):

- [x] Emoji Menu
- [x] Stream Buttons
- [ ] Stickers
- [ ] Remove Profile Upsell
- [ ] Profile Accents
- [ ] Client Themes

Unaffected:
Fake Profile Themes
Preferred Codec
Remove Screen Share Nitro Upsell
Change PremiumType

**Comment by thu2468** [comment]
emoji menu still not working everything grayed out still

**Comment by riolubruh** [comment]
bro this is a work in progress checklist.... it's just so you can know how far i am in fixing it. it hasn't been released yet

**Comment by riolubruh** [comment]
Alright, for now the only thing I can't remove is the upsell on the profile customization screen and since it's not all that important, I'll release the current version with the fixes.
