### ISSUE TITLE
Emoji Matching not working

### ISSUE THREAD

**Issue by ExtosNex** [riolubruh/YABDP4Nitro#127]
The emoji matching popup does not work

Typing `:custom_emote:` does not reveal a list of emoji options

**Comment by ExtosNex** [comment]
Just read that this was on WIP checklist 
https://github.com/riolubruh/YABDP4Nitro/issues/122#issuecomment-1689163606

**Comment by riolubruh** [comment]
also this is a Duplicate of #128
