### ISSUE TITLE
Emote suggestion/searching is not working

### ISSUE THREAD

**Issue by minhla** [riolubruh/YABDP4Nitro#128]
When you type ":" and some words, normally there will be a popup showing the emoji results. But right at 4.7.0 it's not working.
The searching functionality inside the emoji popup is not working as well.

Discord version: Stable 222139 (68d455a)

**Comment by MikevanBreePXL** [comment]
+1, got broken after the latest update

Stable 222139 (68d455a)
Windows 10 64-Bit

**Comment by riolubruh** [comment]
Will be fixed in the next update
