### ISSUE TITLE
Streaming not working

### ISSUE THREAD

**Issue by BJack0** [riolubruh/YABDP4Nitro#133]
![image](https://github.com/riolubruh/YABDP4Nitro/assets/64874028/eb246907-af50-40fe-af39-42cc2b42f954)

Like the title says, options for video quality and framerate are locked behind nitro.

**Comment by riolubruh** [comment]
The issue is known about. See #132 for a workaround until the issue is resolved.

**Comment by riolubruh** [comment]
Okay I figured out the issue, and I'm honestly a little embarrassed that I didn't notice this sooner.
The `customVideoSettings` function doesn't run unless either Custom Resolution or Custom FPS is enabled, even if High Quality Screensharing is enabled, which wouldn't be a problem if the name of the function was a little less misleading, however, 
customVideoSettings is also the function that unlocks the stream quality buttons... woops!

**Comment by BJack0** [comment]
Thanks
