### ISSUE TITLE
When i put the plugin into the plugins folder it says "META not found"

### ISSUE THREAD

**Issue by LerpCat** [riolubruh/YABDP4Nitro#135]
Please Help I Really Love this plugin
![image_2023-08-27_100651304](https://github.com/riolubruh/YABDP4Nitro/assets/143298996/f1d9d885-4baf-4937-89fa-2a29f7eaa72a)

**Comment by riolubruh** [comment]
Please read the FAQ at #76.
tl;dr: Please delete and redownload the plugin to fix the issue.

**Comment by LerpCat** [comment]
i have done this MANY times and it still does not work

**Comment by LerpCat** [comment]
your attached files must be corrupted or im downloading it wrong,

**Comment by riolubruh** [comment]
Looking at the image (below), it looks like you are probably downloading it incorrectly. To download it, go to the raw file at [this url](https://raw.githubusercontent.com/riolubruh/YABDP4Nitro/main/YABDP4Nitro.plugin.js) (which can be found by clicking the file in the repository and hitting "Raw") and press Ctrl+S or right-click and click "Save as". This is the process to correctly download the plugin.

> Please Help I Really Love this plugin ![image_2023-08-27_100651304](https://user-images.githubusercontent.com/143298996/263501740-f1d9d885-4baf-4937-89fa-2a29f7eaa72a.png)
