### ISSUE TITLE
Between me as an app I have revenge when I make more plugins it tells me to put a Code/link which one I put pk I don't understand how to do it 

### ISSUE THREAD

**Issue by Raoul-npbodi** [riolubruh/YABDP4Nitro#138]
![Screenshot_2023-09-14-02-31-06-164_dev beefers vendetta](https://github.com/riolubruh/YABDP4Nitro/assets/143364752/78c1fbbd-3689-4499-bf7c-b0a33e3c9f69)

**Comment by speedlorenzo12** [comment]
1, is named vendetta, 2 this plugin is for betterdiscord

**Comment by riolubruh** [comment]
This plugin is for BetterDiscord and therefore can only be used on the _BetterDiscord client._
