### ISSUE TITLE
Entrance Sounds?

### ISSUE THREAD

**Issue by iGetUploaded** [riolubruh/YABDP4Nitro#140]
Any chance of adding this to it or would it not be possible

![image](https://github.com/riolubruh/YABDP4Nitro/assets/54633753/81054207-1c90-4baf-a7cb-685e1048ff64)

**Comment by riolubruh** [comment]
First I would have to figure out how to play soundboard sounds, which I haven't been able to do (#111).

**Comment by iGetUploaded** [comment]
Ah didnt notice that
