### ISSUE TITLE
ProfileBanners not Working for me and a friend 

### ISSUE THREAD

**Issue by Jujutak-Jr** [riolubruh/YABDP4Nitro#146]
Is it Possible something is broken as i dont see any ProfileBanners besides Nitro ones ? just asking as a friend has the same problem ...
Did everything like its described but it still didnt work with like 4 diff pics/imgur links pasted as 3y3 to the bio . it doesnt show up in the nitro preview either for me and my friend .

**Comment by riolubruh** [comment]
Add me on Discord, `@riolubruh` and I'll help you.
