### ISSUE TITLE
[Bug Report] Enabling YABDP4Nitro breaks the sound effect board

### ISSUE THREAD

**Issue by StShAzzy** [riolubruh/YABDP4Nitro#147]
if you have nitro, that is (and i do have at the time of writing this)
![image](https://github.com/riolubruh/YABDP4Nitro/assets/90798128/f60c90e5-fdc6-496a-b94e-88a944c62bff)

**Comment by riolubruh** [comment]
Send me your config. It could be caused by having Change Premium Type or App Icons enabled, so try disabling those if they are enabled.

**Comment by riolubruh** [comment]
Please let me know if 4.9.1 resolves the issue!

**Comment by StShAzzy** [comment]
thank you, it appears to be fixed now
