### ISSUE TITLE
Wrong PremiumType

### ISSUE THREAD

**Issue by BlackusPL** [riolubruh/YABDP4Nitro#15]
Change `BdApi.findModuleByProps("getCurrentUser").getCurrentUser().premiumType` from 1 to 2 becouse
1 = Nitro Classic
2 = Nitro
3 = Nitro Basic
https://github.com/riolubruh/YABDP4Nitro/blob/35d6ae1fbd90a5b22ae179a52edb803bc5225562/YABDP4Nitro.plugin.js#L409

**Comment by riolubruh** [comment]
Setting premiumType to 2 causes incompatibility issues with FreeStickers. There is also no benefit to changing it to 2 because screenshare options are now unlocked manually

**Comment by riolubruh** [comment]
(Works as intended.)
