### ISSUE TITLE
Custom screenshare get patched

### ISSUE THREAD

**Issue by BebroNUXXX** [riolubruh/YABDP4Nitro#150]
i cant turn on/off plugin settings, custom screenshare won't turn on. Also custom profile or free emoji features dont work
Also this things happen on PTB version of discord after update

**Comment by riolubruh** [comment]
Looks like the update changed some class names. I'll fix it right away.

**Comment by riolubruh** [comment]
Basically: don't worry, nothing has been patched, the plugin just ran into an error.
