### ISSUE TITLE
New Discord rewrite broke alot of stuff

### ISSUE THREAD

**Issue by lucifier99** [riolubruh/YABDP4Nitro#152]
emoji theme all cant be enabled

**Comment by xodotLBO** [comment]
Also half of the features aren't working such as Themes.

**Comment by FragsAreUs** [comment]
I was able to use the nitro themes just fine using the bypasser

**Comment by xodotLBO** [comment]
> I was able to use the nitro themes just fine using the bypasser

Explain further if possible, I tried but it did not work

**Comment by FragsAreUs** [comment]
can't really explain further as for me it just works, I was able to go to the appearance and just select the theme I want to use.

**Comment by xodotLBO** [comment]
What kind of bypasser did you use then?

**Comment by lucifier99** [comment]
share us ur plugins then

**Comment by FragsAreUs** [comment]
I am using the same one from this repo.
![image](https://github.com/riolubruh/YABDP4Nitro/assets/32180105/6f15ae4b-d1b2-4c20-81ee-5e24d7ba1cb5)

**Comment by xodotLBO** [comment]
Guess you are right, I reloaded with this repo and its working again. Interesting. Thanks

**Comment by riolubruh** [comment]
Some bits and pieces of the plugin _may or may not_ still work, but generally speaking most stuff will currently not function. Please be patient as the BetterDiscord devs fix everything, so then I can subsequently begin working on fixing all of the broken stuff.

**Comment by 3941** [comment]
There was a bit of a stealth update of the library, 11 hours ago. Now at least it'll load.
Most features seem to be broken, though.
No emote bypass, though it'll still post a link of those you have normal access to. Won't upload as image, though.
Screenshare options also not working.

**Comment by lucifier99** [comment]
thanks noted for latest update 👍
