### ISSUE TITLE
Nitro Client Themes

### ISSUE THREAD

**Issue by Ububacka** [riolubruh/YABDP4Nitro#156]
Nitro Client Themes selection are not saved after restarting the application

**Comment by google0101-ryan** [comment]
To add to this, the theme also seems to reset at random while using the app. Applying any gradient theme also seems to reduce performance.

Hardware:
CPU: AMD Ryzen 3 3200G
GPU: AMD RX480 4GB
RAM: 16GB DDR4 Corsair Vengeance LPX
OS: Windows 11 Home version 22621.2428

**Comment by tepattaja** [comment]
And to add to this more, the themes and custom app icon changes back to normal every single time you change your online status. For example from Online to idle.

**Comment by riolubruh** [comment]
Yeah I couldn't figure out how to get this bypass working perfectly before release. I'll continue working on it!

**Comment by speedlorenzo12** [comment]
for me every now and then on canary the themes client deactivates itself for no reason every now and then, I want to understand if it's a conflict or if it's the plug itself

**Comment by speedlorenzo12** [comment]
You are the best 👍

**Comment by riolubruh** [comment]
> And to add to this more, the themes and custom app icon changes back to normal every single time you change your online status. For example from Online to idle. 

As for the app icons, they are still glitchy.
