### ISSUE TITLE
[Bug] Profile Banner 3y3 changes avatar instead.

### ISSUE THREAD

**Issue by Maverynthia** [riolubruh/YABDP4Nitro#158]
![image](https://github.com/riolubruh/YABDP4Nitro/assets/2293000/6bc66d4d-b98e-400e-804a-1dc7dccc6062)
This is the avatar before I put the Imgur in the Profile banner slot. Expected: Banner changes
![image](https://github.com/riolubruh/YABDP4Nitro/assets/2293000/427f0300-8855-4f54-acea-2a124cdc9080)
Avatar changes to the banner instead of the banner.

I understand this might be due to the Discord breaks.

**Comment by riolubruh** [comment]
The issue is known about and will be fixed in the next release.

**Comment by Maverynthia** [comment]
Thanks, appreciate it
