### ISSUE TITLE
FreeStickers

### ISSUE THREAD

**Issue by jmytch** [riolubruh/YABDP4Nitro#163]
I don't know if you are aware that FreeStickers that are forked by you are no longer working, see screen snip.

Yes I did delete the plugin, download the file again and it still have this pop up. Something bonked.

EDIT: Also your fork doesn't allow "Issues" so I couldn't be able to report there, so came here instead.

![Screenshot 2023-11-09 211201](https://github.com/riolubruh/YABDP4Nitro/assets/45726972/6dffbeef-be49-4a47-9685-5a6a83a72f9c)

**Comment by riolubruh** [comment]
The fork doesn't allow issues because I do not want to fix issues with FreeStickers.
