### ISSUE TITLE
[Feature Requests] Super Reactions

### ISSUE THREAD

**Issue by FortNbreak** [riolubruh/YABDP4Nitro#170]
I know this is probably not possible and if it is, it would be a pain in the ass but yea it would be a pretty amazing feature.

So what this would do is make it to where you could react with the well-known super reactions or whatever they are called and other YABDP4Nitro Users could see them and react with the same thing. It would be pretty insane and a feature that I have never seen before but sounds interesting 👍

**Comment by abc123r** [comment]
yeah your right is there any bug fix

**Comment by abc123r** [comment]
Ok, thanks. But cna you make that feature? Please, it would be so good

**Comment by riolubruh** [comment]
> There's not really any reasonable way that this could be achieved, afaik. The data for these custom reactions would need to be saved somewhere — primarily, a list of users that reacted for each message. The dev would have to host his own backend to store and fetch this data.
> 
> The only alternative would be some sort of janky hack that requires 2 reactions for 1 super reaction — the first being the reaction you selected, and the second being some random default (and ideally rarely used) emoji that's hidden and used as an identifier (let's call it a pseudo-reaction) for the desired super reaction effect.
> 
> Example:
> 
> * The dev would pick a bunch of typically unused emojis and assign an effect to each one (i.e.: 👨🏾‍🤝‍👨🏻 for UFO, 👨🏾‍🤝‍👨🏼 for confetti, 👨🏾‍🤝‍👨🏾 for another dumb effect, etc.)
> * The user would pick an emoji to super react with (let's go with "😍"), and then YABDP4 would follow it up with one of the pseudo-reactions depending on whichever effect you chose.
> * To non-YABDP4 users, it'll show up under the message as `😍` `👨🏾‍🤝‍👨🏻`. But for YABDP4 users, the `👨🏾‍🤝‍👨🏻` would be hidden, and the `😍` would be displayed with a super-reaction effect.
> 
> This would have several issues, however:
> 
> * Non-YABDP4 users can independently click the first reaction or hidden second reaction (pseudo-reaction), causing an imbalance. You could manually compare the list of names to exclude the extras, but that would require you to fetch the list of users that reacted for every single message. Needless to say, that would be a terrible idea.
> * Discord doesn't always send reactions in the correct order. Since this method would rely on the placement of pseudo-reactions to determine with regular reaction to apply the super reaction effect to, users would often encounter it randomly applying effects to the wrong reactions.
> * Non-YABDP4 users could inadvertently create a fake super-reaction by reacting with one of the pseudo-reaction emojis. Additionally, YABDP4 users would be unable to react with whichever emojis were selected to be used as pseudo-reactions.
> * Non-YABDP4 users obviously won't see the fake super reactions and will be confused by why people are spamming seemingly random reaction emojis (i.e. the pseudo-reactions).
> * As with all of the other Tencent garbage Discord has been spewing out, super reactions are nothing but an annoying, laggy gimmick anyway and really aren't worth the time or effort (and definitely not money).

Yeah this pretty much sums it up
