### ISSUE TITLE
DiscordFreeStickers not working

### ISSUE THREAD

**Issue by ThrowawayAccount01** [riolubruh/YABDP4Nitro#172]
Posting this issue here since there is no issues tab in the other repo.

Trying to enable the plugin: https://github.com/riolubruh/DiscordFreeStickers gives the error FreeStickers could not be started.

![error](https://github.com/riolubruh/YABDP4Nitro/assets/125531852/16fb162b-c1b4-4ac5-929e-4b494fe36554)

Think a discord update broke it.

**Comment by riolubruh** [comment]
>ThrowawayAccount01
Nice

**Comment by riolubruh** [comment]
To address your issue, as explained in #169, I really didn't want to fix any issues for that plugin; An0 is really the one who should be doing so, but since An0 takes like 100 years to fix their plugins, I'll consider it.

**Comment by riolubruh** [comment]
Progress update: so far I have gotten the plugin to start up, but nothing gets uploaded yet.

**Comment by riolubruh** [comment]
https://github.com/riolubruh/DiscordFreeStickers/commit/de097be870bd74c4a4bbbdeeb436d82820651f3d
