### ISSUE TITLE
link ?

### ISSUE THREAD

**Issue by RadS-DISCORd** [riolubruh/YABDP4Nitro#180]
i cnat find the download link anywhere 
could you give it to me ?
THanks

**Comment by RadS-DISCORd** [comment]
also, im on mac

**Comment by riolubruh** [comment]
right here:
https://raw.githubusercontent.com/riolubruh/YABDP4Nitro/main/YABDP4Nitro.plugin.js
you can right click and hit "Save As" at this url to download it.

**Comment by RadS-DISCORd** [comment]
thabks brooooo
