### ISSUE TITLE
[BUG] Screen share lag

### ISSUE THREAD

**Issue by FoGTeR** [riolubruh/YABDP4Nitro#181]
When the plugin is enabled, the screen demonstration lags. Severe freezes

**Comment by Melanderz** [comment]
Can confirm that i have problem with lagging and kinda skipping while screensharing, do not matter what resolution or fps i´m doing but it goes away as soon i turn off the plugin.

**Comment by riolubruh** [comment]
I did experience a bit of skipping myself actually while I was screen sharing recently, now that I think about it. I'll try to figure out what code is causing it.

**Comment by 3941** [comment]
As long as you don't touch custom bitrate/fps or anything like that, streaming is just fine.
I'm starting to believe they limited it server side and that's it. No more screwing around.
You still get more bitrate on boosted/community servers, apparently.

**Comment by Omniphantasm** [comment]
Can confirm I got this issue as well and its **bad**

If I screenshare on Vanilla Discord it's perfectly fine no FPS issues. If I try to screenshare with YABD it'll work fine but entirely randomly it will suddenly drop framerate to like 2-5 FPS for 5-30 seconds before going right back to 144 FPS. This sporadic framerate issue continues until I log out and back into my Windows account at which point the FPS is perfectly fine unless I try to stream again at which point the sporadic issues return. 

This doesn't happen if I use OBS to stream to Twitch at the same res/framerate though so seems to be something directly related to this plugin since its only one I'm using.

**Comment by 3941** [comment]
You can stream 144fps on vanilla?

**Comment by riolubruh** [comment]
Yeah FPS's that high are _way_ too much for Discord to handle. Reminder that discord streaming is only designed with 60fps in mind. There's probably not much I can do as a plugin developer to prevent screen share issues if the users are the ones setting the options to absurd levels. Keep your bitrates, framerates, and resolutions realistic and Discord will behave. This issue mostly serves as a warning for people to not go crazy with the settings.

**Comment by Omniphantasm** [comment]
Thing is it was fine until like the past month or so. I'm only streaming it
at 60 fps 1080p and was never an issue. Now it just suddenly starts
randomly tanking frame rate for 5 to 30 seconds at a time before going back
to normal. Not sure what changed or when though but it's 100 percent
something that either changed with plugin or that discord themselves fucked
up. If I stream on a legit nitro account with same settings it doesn't
happen so I got no idea wtf is going on.

**Comment by 3941** [comment]
Hmmm... I do know that streaming high source framerates can be an issue for streams. Depending on the game, you might wanna limit your FPS. But the issues are usually with the stream, not the game, getting choppy.

I don't really stream games. Mostly just movies for a small community (we do a movie night every week). And I don't have any issues with YABDP4Nitro (as long as I leave custom settings alone and only use the Nitro quality option). Streams are smooth and so is everything on my end. But I'm also not running my system at its limits, which high fps gaming will do to most systems.

**Comment by Omniphantasm** [comment]
Yeah I dunno, its just an issue that suddenly cropped up for me. Before a month or so ago it was working flawlessly. Now literally any game even if its something as simple as Resident Evil 5 which my system should be able to run like 5-6 copies of with no issue will just randomly tank framerate. 

As for encoding I've tried the various ones on OBS and never run into the same issue. Maybe I just got a messed up install of Discord or something and need to wipe it entirely/reinstall it. Its only games that cause the issue though, I can stream movies/TV/Desktop just fine. Second I do a game though it just kills the framerate for the whole system, even if I alt tab out my mouse is a chunky mess like my whole system is overloaded which is frankly impossible on my system.

Probably just some weird damn bug I've ran into.

**Comment by riolubruh** [comment]
Indeed, not much has changed on the plugin's end for quite some time. I think issues like this only started appearing after I made some changes to how quality ladders work, though. Maybe that's part of the issue?

**Comment by riolubruh** [comment]
Attached is a version of YABDP4Nitro with all changes to the ladder commented out.
Please try this version and tell me if it helps the issue.
[YABDP4Nitro.plugin.zip](https://github.com/riolubruh/YABDP4Nitro/files/15079993/YABDP4Nitro.plugin.zip)

**Comment by Omniphantasm** [comment]
With a cursory test of about an hour of gameplay on Jusant where it was happening the most consistently and frequently I haven't had it happen since tossing that one in. I'll update if it does happen again but so far so good.

**Comment by riolubruh** [comment]
(Newest update shadow dropped the removal of the ladder changes)
