### ISSUE TITLE
Can anyone else see my badge?

### ISSUE THREAD

**Issue by SeongGyu1216** [riolubruh/YABDP4Nitro#183]
![image](https://github.com/riolubruh/YABDP4Nitro/assets/124080614/dbc74939-513d-4df0-9fa2-dad9f5c0dc3d)

Can anyone else see the badge that comes up when you click on a profile, like a photo?
Or is it only visible to people who are using that plugin?

And only those who are using the YABDP4Nitro plugin can see the Custom profile?

**Comment by riolubruh** [comment]
Only other users of the plugin can see these profile modifications.
