### ISSUE TITLE
Windows defender has been recently detecting YABDP4Nitro.plugin.js as a malware

### ISSUE THREAD

**Issue by StShAzzy** [riolubruh/YABDP4Nitro#186]
probably not something you can do something about, this is more to point out the problem and give users a heads-up that it's just a false-positive

**Comment by riolubruh** [comment]
That's strange. I believe there's a way to report detections as false positives somewhere on a Microsoft website, but I'm not sure.

**Comment by StShAzzy** [comment]
problem solved, Windows Defender shows that the file is safe now
