### ISSUE TITLE
Windows Defender false positive

### ISSUE THREAD

**Issue by minhla** [riolubruh/YABDP4Nitro#188]
When I download the plugin my Windows Defender immediately detects the file as containing trojan `Trojan:Win32/MalUri.A!cl`
![image](https://github.com/riolubruh/YABDP4Nitro/assets/23179654/8e8a50c3-6c5b-441b-bb10-ed7075c4b109)

**Comment by riolubruh** [comment]
I have sent the file to Microsoft to report the false detection using [this](https://www.microsoft.com/en-us/wdsi/filesubmission). That's all I can really do about it at the moment. It might help if more people are able to report it with more information such as the definition version which I don't have.

**Comment by riolubruh** [comment]
The website claims that **latest Windows Defender definitions apparently don't detect it**.
![chrome_34CiM04DC2](https://github.com/riolubruh/YABDP4Nitro/assets/54255074/4405b6d0-30b9-4e93-bde7-4d2e5f0dfd19)
I imagine that your definitions may be out of date. You can learn how to update them [here](https://www.microsoft.com/en-us/wdsi/defenderupdates).

**Comment by minhla** [comment]
I am already at the latest definitions version `1.407.529.0`
![image](https://github.com/riolubruh/YABDP4Nitro/assets/23179654/de6ba569-f9c0-4311-ad9c-d0b3e7e105a8)

**Comment by riolubruh** [comment]
I figured that the Microsoft website was probably lying to me. I hope they fix this soon.

**Comment by Rockdag** [comment]
Brother, I haven't been on discord in months, and I don't even have a
fucken PC lmfao

**Comment by riolubruh** [comment]
wut?
