### ISSUE TITLE
Could You Add Custom Screenshare Audio device so i can select a specific input or output device i want going to my screenshare so that you can have audio working on full screenshare and also be able to have audio on games that have broken audio on discord screenshare

### ISSUE THREAD

**Issue by Pickymarker** [riolubruh/YABDP4Nitro#19]
Could You Add Custom Screenshare Audio device so i can select a specific input or output device i want going to my screenshare so that you can have audio working on full screenshare and also be able to have audio on games that have broken audio on discord screenshare

**Comment by Pickymarker** [comment]
also my screenshare reverts to 720p 30 fps sometimes after a little when using bdcompat for discord kernel

**Comment by riolubruh** [comment]
I found a way to change the PID of the program that the audio is shared from. I hope that will suffice
