### ISSUE TITLE
[Bug Report] Nitro User's Animated Profiles Stops Animating if YABDP is Enabled

### ISSUE THREAD

**Issue by StShAzzy** [riolubruh/YABDP4Nitro#190]
user's profile pictures don't animate for every user who has one
~~same goes for banners~~ used to

not animating when enabled
![broken](https://github.com/riolubruh/YABDP4Nitro/assets/90798128/417f083e-e507-4099-a119-1a76781e2fe5)

animating when disabled
![animated](https://github.com/riolubruh/YABDP4Nitro/assets/90798128/9fc7a2f3-c0e2-4637-acfb-c8694b4a12ea)

**Comment by StShAzzy** [comment]
do you think it's a easy fix? my friend suggested me to try and fix it and then open a PR, but i got no idea on where to start, so... depending on your answer i could give a try at JS, althrough i got minimal idea on how i code on it

**Comment by riolubruh** [comment]
Should be fixed in latest patch.

**Comment by StShAzzy** [comment]
i'm sad to announce to you, that... it only fixed banners

**Comment by StShAzzy** [comment]
or discord is just fucking with me because of cache

**Comment by StShAzzy** [comment]
weird... some animate, some don't
for instance the user i showed off in the gifs, animated the banner, but not the profile picture, but the profile picture of Carl-Bot (the bot) does animate, for whatever reason

**Comment by riolubruh** [comment]
Honestly I don't have any way to test real nitro animated profile pictures cause i have no friends lol

**Comment by StShAzzy** [comment]
i don't have nitro at the time... but i can still find some people random people to test this with, or just bother my friend with it
