### ISSUE TITLE
delete it pls

### ISSUE THREAD

**Issue by deadcutiecat** [riolubruh/YABDP4Nitro#191]

**Comment by riolubruh** [comment]
no

**Comment by riolubruh** [comment]
To answer the question that you initially asked but then deleted, the plugin does not take any user information such as user IDs.

**Comment by riolubruh** [comment]
Unfortunately, I don't really have any recommendations on avoiding malicious JS code.
I usually do a glance over the code to make sure nothing is fishy.
If it's obfuscated in any way I wouldn't risk it. (Compiled TypeScript is an exception)
Other than that, though, I sort of just make sure it doesn't blatantly try to grab tokens.

**Comment by deadcutiecat** [comment]
No worries, thanks for the heads up!
