### ISSUE TITLE
[Bug Report] Going into the shop tab causes the client to crash

### ISSUE THREAD

**Issue by StShAzzy** [riolubruh/YABDP4Nitro#192]
i should probably insert a gif here... maybe later

**Comment by riolubruh** [comment]
lol

**Comment by riolubruh** [comment]
Disabling all other plugins causes the issue not to happen, so I'm not sure what is causing it. Maybe a conflict?

**Comment by StShAzzy** [comment]
only wish i knew a stacktrace for this sort of thing

**Comment by StShAzzy** [comment]
one thing is for sure, it always causes a crash on my client, whenever the shop fully loads

**Comment by StShAzzy** [comment]
alright... it's probably a conflict, time to hunt down the faulty plugin

**Comment by StShAzzy** [comment]
i loaded all the plugins i usually do, and it didn't crash, maybe it's something to do with loading the page, and not actually displaying it

**Comment by StShAzzy** [comment]
https://github.com/riolubruh/YABDP4Nitro/assets/90798128/226406f7-8dcc-4215-b1ee-262fd89d3812

**Comment by StShAzzy** [comment]
unloaded everything but this plugin... yet it still caused some crashes on me...

**Comment by riolubruh** [comment]
I've found that the crashes are really weird and inconsistent.

**Comment by riolubruh** [comment]
Found the cause.
