### ISSUE TITLE
YABDP4Nitro: What the fuck happened..? During buttonCreate()

### ISSUE THREAD

**Issue by Ipertatos** [riolubruh/YABDP4Nitro#196]
discord crashing when clicking on a server or a DM.

`TypeError: Cannot read properties of undefined (reading 'appendChild')

 at YABDP4Nitro.buttonCreate (YABDP4Nitro.plugin.js:1888:87)`

**Comment by Ipertatos** [comment]
Ok i tested it there is no interferenc with the theme i am using or any other theme

**Comment by Ipertatos** [comment]
ok after testing all the plugins JumpToTop seems like the problem. Will try to find fix.

**Comment by riolubruh** [comment]
The issue is with JumpToTop.
