### ISSUE TITLE
New codec?

### ISSUE THREAD

**Issue by itsTyrion** [riolubruh/YABDP4Nitro#197]
Hi, I noticed this on someone else's screenshare today. Does Discord allow H.265 for screenshare now? 
![image](https://github.com/riolubruh/YABDP4Nitro/assets/17730120/f28b245a-f1cb-47bb-a70b-901367a1f52c)
The person has Nitro and, apparently, no clientmods and runs Windows.
Is this something you might be able to look into? I've also noticed "Allow H265 codec" in the mobile app for some months (iOS/Android)

**Comment by itsTyrion** [comment]
I console-logged `e.codecs` in the `updateVideoQuality` hook and it does in fact have H265: 
vq-debug: [
  {
    "type": "audio",
    "name": "opus",
    "priority": 1,
    "payloadType": 120
  },
  {
    "type": "video",
    "name": "AV1",
    "priority": 3,
    "payloadType": 101,
    "rtxPayloadType": 102,
    "encode": false,
    "decode": false
  },
  {
    "type": "video",
    "name": "H265",
    "priority": 2,
    "payloadType": 103,
    "rtxPayloadType": 104,
    "encode": false,
    "decode": false
  },
  {
    "type": "video",
    "name": "H264",
    "priority": 4,
    "payloadType": 105,
    "rtxPayloadType": 106,
    "encode": false,
    "decode": false
  },
  {
    "type": "video",
    "name": "VP8",
    "priority": 1,
    "payloadType": 107,
    "rtxPayloadType": 108,
    "encode": true,
    "decode": true
  },
  {
    "type": "video",
    "name": "VP9",
    "priority": 5,
    "payloadType": 109,
    "rtxPayloadType": 110,
    "encode": true,
    "decode": true
  }
]

**Comment by riolubruh** [comment]
Discord has been working on H265 for a long time it seems. Did they finally release the codec without any fanfare?

**Comment by itsTyrion** [comment]
Maybe? The mobile app had a setting for allowing to view H265 streams for like... 3/4 of a year?

I saw the screen share switch to H264 later after more people joined and I *think* it went back later? Which would match the behavior on adapting to the client with the worst connection.
