### ISSUE TITLE
[Bug Report] Emojis on servers that had more than 50 slots aren't bypassed

### ISSUE THREAD

**Issue by StShAzzy** [riolubruh/YABDP4Nitro#198]
so basically, servers that had Nitro and used the extra slots for emojis and then expired their nitro, don't get bypassed

**Comment by riolubruh** [comment]
An issue existed for this in the past (#64), but I closed it because I assumed that I'd accidentally added it by patching the `getEmojiUnavailableReason` function to always return undefined, but apparently that was an incorrect assumption. Whoops...

**Comment by StShAzzy** [comment]
sure thing.
`https://discord.gg/Fvp6cS2a`
