### ISSUE TITLE
is there a way to add custom encoder selection to like be able to pick other encoders nvenc,hevc h265 and h264 and etc.

### ISSUE THREAD

**Issue by Pickymarker** [riolubruh/YABDP4Nitro#20]
is there a way to add custom encoder selection to like be able to pick other encoders nvenc,hevc h265 and h264 and etc.

**Comment by riolubruh** [comment]
Since H.264 is the default and is typically regarded as the best of those options (H.264, VP9, VP8, AV1X), I don't really see much of a reason to implement a way to change which codec is used.

**Comment by Pickymarker** [comment]
but what about nvenc

**Comment by riolubruh** [comment]
It's not implemented in Discord's screen share
