### ISSUE TITLE
Custom emotes not usable with latest plugin update and nitro basic

### ISSUE THREAD

**Issue by itsTyrion** [riolubruh/YABDP4Nitro#200]
I have a nitro basic sub. Since the latest update, I can no longer use custom/animated emotes with the plugin active. (I use it for screenshare bitrate)
![image](https://github.com/riolubruh/YABDP4Nitro/assets/17730120/84e3c46b-0b5a-40f8-9bb3-802c28f286e5)
![image](https://github.com/riolubruh/YABDP4Nitro/assets/17730120/cd9a781e-d09d-48af-9fb0-36b140b6eaec)

**Comment by riolubruh** [comment]
There was a typo in the canUserUse patch in 5.3.1. It has been corrected in 5.3.2. Let me know if this resolves the issue!

**Comment by itsTyrion** [comment]
yup, bug is fixed, thanks
