### ISSUE TITLE
Needs manifest folder of a file manifest.json

### ISSUE THREAD

**Issue by Rax-shiftware** [riolubruh/YABDP4Nitro#201]

**Comment by riolubruh** [comment]
wut? Please take a screenshot of the error.
Additionally, try deleting and reinstalling the plugin

**Comment by Rax-shiftware** [comment]
Hey! I did but it shows that no manifest provided.

I installed the plugin to Aliucord (like discord) page and this happened:

**Comment by riolubruh** [comment]
This is not an Aliucord plugin.
This plugin is only for BetterDiscord on PC.
