### ISSUE TITLE
[Feature request] App icons

### ISSUE THREAD

**Issue by fvvwrd** [riolubruh/YABDP4Nitro#202]
Can you add the nitro app icons? Thank you for the plugin. 
Edit. I have seen it mentioned in a closed issue https://github.com/riolubruh/YABDP4Nitro/issues/142
But as of 28.04.2024 I don't see how to apply changes. Instructions for mac would be appreciated

**Comment by riolubruh** [comment]
Not sure how it works on Mac.
If you're referring to the in-app icon in the top left, go to Settings>Plugins>YABDP4Nitro>Miscellaneous and enable App Icons, then go to Settings>Appearance to change it there.
If you're referring to the actual icon of the application you would see in your taskbar for instance, I dunno cause I don't use Mac. Google it if that's what you're looking for.

**Comment by riolubruh** [comment]
Bumping this issue. @fvvwrd are you alive?

**Comment by fvvwrd** [comment]
I guess I'll have to reinstall the app since I cannot enter the BD settings. Sorry for late reply

**Comment by fvvwrd** [comment]
Yeah I meant the icon inside the app near chats

**Comment by riolubruh** [comment]
Forgot to close this issue. The feature is already in the plugin.
