### ISSUE TITLE
[Bug Report] File Upload with Emoji causes bypass to fail

### ISSUE THREAD

**Issue by StShAzzy** [riolubruh/YABDP4Nitro#206]
hello, one more time
if you embed a image in a message you're sending and insert a emoji on the message the bypass fails completely
the image is send and the emoji is sent as regular text

if for whatever reason it's not possible to send both on the same message, could you add a warning pop-up about it?

**Comment by riolubruh** [comment]
I believe the reason for this is because when sending a file the client uses the uploadFiles function instead of the sendMessage function, and none of the emoji bypasses patch the uploadFiles function.

**Comment by riolubruh** [comment]
@StShAzzy Let me know your opinion on this: should the emoji be in a *separate message* or attached to the same message as the file?

**Comment by StShAzzy** [comment]
yeah, that the problem with the maximum attachment limit would be pretty annoying to deal with so... i guess attaching the emoji sending a new message with the bypass emoji would be enough, althrough, you could still append the emoji to the current message depending on how many files the user is sending

**Comment by StShAzzy** [comment]
also, if you ever get boring of waiting for me to answer, you can just send the message on discord, we still share a single server _(T.C.R.F)_
