### ISSUE TITLE
Can't change Avatar w/ Imgur link

### ISSUE THREAD

**Issue by Sciccorz** [riolubruh/YABDP4Nitro#209]
Pasted mutliple imgur links into the bar and coped and pasted the 3y3 text but nothing changes. All of the other 3y3 text for banner etc work fine

**Comment by riolubruh** [comment]
paste avatar 3y3 into custom status

**Comment by Sciccorz** [comment]
> paste avatar 3y3 into custom status

Already tried it and didn't  change pfp

**Comment by riolubruh** [comment]
That's weird; it works fine for me. Join my Discord server so we can debug it easier.
