### ISSUE TITLE
Can't see avatar decorations

### ISSUE THREAD

**Issue by Yapper27** [riolubruh/YABDP4Nitro#211]
![image](https://github.com/riolubruh/YABDP4Nitro/assets/83966481/d4710b4b-c220-490a-a4d5-4d6d31f922c7)

**Comment by samano0330** [comment]
Thank you for sharing your wonderful project.🎉
but I have the same issue.
I would appreciate it if you resolve this problem.

**Comment by riolubruh** [comment]
Is this problem resolved? I made some changes to Avatar Decoration fetching in the last update.

**Comment by samano0330** [comment]
Thank you @riolubruh 
checking now.

**Comment by riolubruh** [comment]
Earlier today, I released an update which totally reworks how the plugin fetches avatar decoration data. Hopefully this means that this issue is finally resolved, but I won't know unless someone encounters it again ( or doesn't ).
