### ISSUE TITLE
Discord update broke a bunch of modules

### ISSUE THREAD

**Issue by B-Wilhelm** [riolubruh/YABDP4Nitro#214]
![image](https://github.com/riolubruh/YABDP4Nitro/assets/12756875/57fd0b46-26dd-4e2c-ae39-7a6f5205279b)
for reference: 
![image](https://github.com/riolubruh/YABDP4Nitro/assets/12756875/9d9428f4-5940-44bc-a3e6-1735fc5a6c4b)

**Comment by SalSlice** [comment]
Same thing happening to me :(. I think It's because Better Discord had an update about 2 hours ago.

**Comment by B-Wilhelm** [comment]
Ah good catch, didn't even notice.
