### ISSUE TITLE
Gridinsoft false positive

### ISSUE THREAD

**Issue by Hiroiscoding** [riolubruh/YABDP4Nitro#215]
https://media.discordapp.net/attachments/1017265804045201510/1252856341450588192/image.png?ex=6673bce4&is=66726b64&hm=8aa008c927c42f4baba92c7d16f09d23247c9cc1ff8ab55e6fe5b4ce5883f2c8&=&format=webp&quality=lossless&width=1588&height=889 
Saying that its malware.

**Comment by riolubruh** [comment]
A false positive _again_? First, it happened with Windows Defender...
