### ISSUE TITLE
cant select nitro client themes

### ISSUE THREAD

**Issue by speedlorenzo12** [riolubruh/YABDP4Nitro#217]
![Screenshot 2024-06-20 182204](https://github.com/riolubruh/YABDP4Nitro/assets/111771663/337e4fa7-709f-4650-8f42-0fc22137b351)

**Comment by riolubruh** [comment]
That's weird. It works fine for me, and even so, the gradient themes and app icons should be showing underneath the default ones, ex:
![Discord_j49bYQpU4W](https://github.com/riolubruh/YABDP4Nitro/assets/54255074/8a27b515-4136-41fd-bc93-9d606c9c3de2)
Except locked if the plugin was not working properly.
