### ISSUE TITLE
Transmitting at higher FPS, crashes the discord of the person watching.

### ISSUE THREAD

**Issue by zairoxtv** [riolubruh/YABDP4Nitro#219]
![NVIDIA_Overlay_7AjXyXLVaU](https://github.com/riolubruh/YABDP4Nitro/assets/63269597/56b039e0-b323-4ce7-809c-e69488cd60ad)
v5.4.2

The problem has been occurring for several versions now and has unfortunately still not been fixed.

**Comment by Yuchenjimmy** [comment]
You should take a look at the issue titled as "PSA: Vanilla/unmodded Screen Share Viewer crashes when viewing a stream with a custom resolution or FPS".

**Comment by riolubruh** [comment]
Duplicate of #213.
