### ISSUE TITLE
userbg integration works but the banner is not updated

### ISSUE THREAD

**Issue by speedlorenzo12** [riolubruh/YABDP4Nitro#220]
I had a semi-corruption of the banner due to the change in the source in which the banners are stored, I updated it 2 times but it remained the same as the first time, could you give me a possible solution or you do a possible correction? (from og plugin works correctly) (and I saw that experiments no longer appear)

**Comment by riolubruh** [comment]
What does this even mean

**Comment by speedlorenzo12** [comment]
old banner (YABD4NITRO) (black schreen for a second)
![Screenshot 2024-06-29 075618](https://github.com/riolubruh/YABDP4Nitro/assets/111771663/3557a815-bcaa-4641-9150-94514a633c85)
new banner (other clients and og usrbg the latest and correct banner)
![Screenshot_2024-06-29-07-57-08-865_](https://github.com/riolubruh/YABDP4Nitro/assets/111771663/269117c0-de7e-455c-934e-56a1b31e41bd)

**Comment by riolubruh** [comment]
Looks like the Vencord UsrBG plugin has some CSS that expands the banner area. I have added it.

**Comment by speedlorenzo12** [comment]
I found the origin of the strange bug, for some reason the id selector gets the wrong image and takes the old one, it's a bug in the plugin itself not other plugins

**Comment by riolubruh** [comment]
I don't understand; you say it's the wrong image, but the screenshots you sent literally have the same image in both, just cropped differently..? All the plugin does is check if a user is registered in the UsrBG database and, if they are, returns the banner URL as
`https://usrbg.is-hardly.online/usrbg/v2/${user.userId}?size=4096`, which, as far as I can tell, ***is identical to the*** [***Vencord implementation***](https://github.com/Vendicated/Vencord/blob/main/src/plugins/usrbg/index.tsx#L120)...?

**Comment by speedlorenzo12** [comment]
they are not the same, maybe I explained it wrong.  the edges are not cut well and you can see a light color that has nothing to do with it and at the end of the gif everything is shown black, so I had to make a second request
