### ISSUE TITLE
Screenshare custom res and FPS dont take effect

### ISSUE THREAD

**Issue by my23aba** [riolubruh/YABDP4Nitro#222]
I can't seem to get the plugin to take effect. I have installed it as instructed, changed the custom resolution and fps settings in the plugin, but no matter what I do it doesn't change the stream's resolution or fps. I've even tried turn on the "Stream Settings Quick Swapper" option and tried changing the settings from there, but the stream remains unaffected. :/

**Comment by riolubruh** [comment]
Until the screen share remote crashing problem is fixed, maybe it's best this issue remain unsolved...

**Comment by riolubruh** [comment]
Currently there is an issue where the plugin seemingly does not prompt the user to download ZeresPluginLibrary like it should. Please install ZeresPluginLibrary manually until the issue can be investigated.

**Comment by riolubruh** [comment]
For the record, I am not experiencing this bug. It seems to be working fine and I haven't had any other reports.
Please note that the Custom Resolution and Custom FPS toggles are set to Disabled by default.

**Comment by riolubruh** [comment]
Stale issue. Seems to work fine for me. Please check your configuration. If you are still experiencing this issue, please reply or otherwise get in contact!
