### ISSUE TITLE
Incorrect labels for custom bitrate 

### ISSUE THREAD

**Issue by Brustachio** [riolubruh/YABDP4Nitro#224]
![image](https://github.com/user-attachments/assets/b5c72171-923c-4626-93f3-be90bb350e03)

The target bitrate being labeled as default 2500kbps makes no sense as it is stated that the maximum bitrate is labeled as default 600kbps. I believe these descriptions are flipped? 

It seems the actual minBitrate, maxBitrate, and targetBitrate I type into the boxes work, but the descriptions threw me off a little if I'm not mistaken.

**Comment by riolubruh** [comment]
holy shit how did i never notice this

**Comment by riolubruh** [comment]
i think when I was writing the descriptions, I thought that the maximum was the bottom one and the target was the middle (which is really what it should be) and just never noticed
