### ISSUE TITLE
[feature]show all utility message buttons

### ISSUE THREAD

**Issue by speedlorenzo12** [riolubruh/YABDP4Nitro#231]
For a year I wanted to use this plugin, however, it has never been updated and now it is 2 years that is completely broken (it is an official plugin), the reason, it is aesthetically beautiful and it is quite comfortable.
I would call it Show All Message Utulilities in the settings.
here the preview https://betterdiscord.app/plugins?filter=showallmessage 
the source that inspired me

**Comment by riolubruh** [comment]
Not a Nitro-related feature.
