### ISSUE TITLE
is there a way to add over 720p webcam quality and stuff to discord because webcams on discord are locked to 720p default

### ISSUE THREAD

**Issue by Pickymarker** [riolubruh/YABDP4Nitro#24]
is there a way to add over 720p webcam quality and stuff to discord because webcams on discord are locked to 720p default

**Comment by riolubruh** [comment]
yes

**Comment by riolubruh** [comment]
try out this version, consider it a sneak peak until i get a chance to clean up the code a bit more
[YABDP4Nitro.plugin.zip](https://github.com/riolubruh/YABDP4Nitro/files/9580729/YABDP4Nitro.plugin.zip)

**Comment by riolubruh** [comment]
releasing a better beta version of this. It's buggy so be cautious.
