### ISSUE TITLE
Won't start/Can't be activated

### ISSUE THREAD

**Issue by JoeyDagger** [riolubruh/YABDP4Nitro#240]
After the Discord update that ruined most plugins for a few days, I haven't been able to start it or use it.

I'm not sure if this issue is known or has been mentioned before, but I haven't seen anything on it yet.

**Comment by riolubruh** [comment]
It's damn near impossible to help you with no error report attached!
I've been seeing a couple of `SyntaxError: Unexpected token '', ""... is not valid JSON` errors that can occur on startup.
If the config is deleted **while Discord is closed**, it will re-generate the config file on next startup, which should fix any errors with the config.
I haven't gotten around to investigating it yet, but when I get the chance I'll see if I can attach some extra error catching to the config-loading commands to hopefully prevent errors like these going forward.
If your error is unrelated to JSON or the config, please provide necessary further information!

**Comment by JoeyDagger** [comment]
After changing the config file name, restarting discord, then changing it back after it updated seemed to fix it. 

Thank you.
