### ISSUE TITLE
0PluginLibrary.plugin.js - deprecated

### ISSUE THREAD

**Issue by Obegg** [riolubruh/YABDP4Nitro#241]
[0PluginLibrary.plugin.js](https://raw.githubusercontent.com/zerebos/BDPluginLibrary/refs/heads/master/release/0PluginLibrary.plugin.js).

According to the [README](https://github.com/zerebos/BDPluginLibrary/blob/master/README.md):

> [!CAUTION]
> This library has reached end of life and is now considered deprecated and discontinued. It is recommended to convert over to using BetterDiscord's built-in API. If you find there are features missing, open a feature request in the BetterDiscord repository.

**Comment by riolubruh** [comment]
It's already no longer in use! I just forgot to remove it from the repo.
