### ISSUE TITLE
About that Discord rewrite...

### ISSUE THREAD

**Issue by riolubruh** [riolubruh/YABDP4Nitro#26]
## **Fixing Everything Checklist**
Emojis: Working
Screen Share Buttons: Unlocked
Custom Resolutions: Fixed
Custom FPS: Fixed
Bitrate: Working
Camera: Haven't Tested

**Comment by Squishyzbear** [comment]
are you going to update the download when plugin is fully fixed , or can you upload the WIP and have it auto update when fixed fully?

**Comment by riolubruh** [comment]
Due to the changes, it doesn't currently seem possible to change the stream quality buttons. There is a way to change the video stream parameters without changing the buttons, however going all the way to the options menu to change it would get annoying pretty fast. I'm gonna consider making a fully custom stream share quality GUI to change the quality, however I would then have to figure out how to actually create said GUI so yeah. I decided not to upload the current WIP build *yet* because multiple features are still not working great.

**Comment by Squishyzbear** [comment]
alright kollkkooolkollkoool thank you for your previous current and future hard work

**Comment by riolubruh** [comment]
SEE NEW UPDATE!!! :DDD
