### ISSUE TITLE
StereoSound

### ISSUE THREAD

**Issue by Pickymarker** [riolubruh/YABDP4Nitro#27]
can you add what this plugin does to your plugin so that we can have the mic quality improvements that this plugin has but be able to use it with the swc update https://www.mediafire.com/file/76xp30pj4dqm9m7/StereoSound.plugin.js/file

**Comment by riolubruh** [comment]
Wouldn't you rather I fix it and manage it separate from this plugin? That way people could use StereoSound without using the Nitro bypasses if they want to.

**Comment by riolubruh** [comment]
Fixed https://github.com/riolubruh/StereoSoundFixed/blob/main/StereoSound.plugin.js

**Comment by riolubruh** [comment]
Turns out, the module that StereoSound is the same one as the setSoundshareSource function, which is used in my plugin! XD
