### ISSUE TITLE
can you make this plugin work with swc https://www.mediafire.com/file/91alc9rgtw81eww/NoSpotifyPause.plugin+(1).js/file

### ISSUE THREAD

**Issue by Pickymarker** [riolubruh/YABDP4Nitro#29]
can you make this plugin work with swc https://www.mediafire.com/file/91alc9rgtw81eww/NoSpotifyPause.plugin+(1).js/file

**Comment by riolubruh** [comment]
looks like just another case of the plugin failing to get the module due to the byProps filter no longer being very useful due to swc

**Comment by riolubruh** [comment]
The original creator fixed it
