### ISSUE TITLE
Stickers

### ISSUE THREAD

**Issue by Chaython** [riolubruh/YABDP4Nitro#30]
Since your plugin is intended as a nitro unlocker, how about stickers? I assume pretty similar to emotes...
This plugin has since stopped working because of the recent discord update, but perhaps inspiration.
https://github.com/An00nymushun/DiscordFreeStickers

**Comment by riolubruh** [comment]
Gonna be completely honest, there's no way I could fix An0's FreeStickers plugin. It's just way too complex for me to wrap my head around. I could make a simple replacement function in the meantime, but it won't be nearly as good as FreeStickers. It might just be better to bug An0 to fix his plugin :/.

**Comment by riolubruh** [comment]
I decided to remove the mention to An0's FreeStickers for now in the README, since it's _still_ broken after all this time.
I'm hoping to get around to making my own system for stickers soon, fingers crossed that it's at least _fairly_ simple.
