### ISSUE TITLE
Activities

### ISSUE THREAD

**Issue by Mag1cTurtle** [riolubruh/YABDP4Nitro#32]
Hello! Will YABDP4Nitro activity be unlocked?

**Comment by riolubruh** [comment]
Maybe

**Comment by Pickymarker** [comment]
adding this would be cool

**Comment by riolubruh** [comment]
It doesn't seem possible. I think they might have added a server side check to this. If you find a way to do it, please let me know!

**Comment by Pickymarker** [comment]
Could this help https://gist.github.com/GeneralSadaf/42d91a2b6a93a7db7a39208f2d8b53ad#gistcomment-4362995 with something
