### ISSUE TITLE
Plugin doesn't work [v4.2.2]

### ISSUE THREAD

**Issue by thiaguinho4** [riolubruh/YABDP4Nitro#33]
Even with emote bypass, sticker bypass and screen share options enabled, the plugin doesn't work

![1](https://user-images.githubusercontent.com/101910294/198408298-69bfa31a-d799-4c05-b2a9-9b678652476e.png)
![2](https://user-images.githubusercontent.com/101910294/198408306-67868cdc-f72b-4d1a-8afb-33b2b60d99b3.png)
![3](https://user-images.githubusercontent.com/101910294/198408317-d58c89f1-c351-4f9c-9b66-84504ba590d8.png)

**Comment by riolubruh** [comment]
Please send an image of any errors in console when the plugin starts, if there are any.

**Comment by thiaguinho4** [comment]
Never mind bro! When BDFDB updated, the plugin now works perfectly.
