### ISSUE TITLE
Activities 

### ISSUE THREAD

**Issue by Pickymarker** [riolubruh/YABDP4Nitro#35]
Could this help https://gist.github.com/GeneralSadaf/42d91a2b6a93a7db7a39208f2d8b53ad with something

**Comment by Pickymarker** [comment]
because i can launch any discord activity using console with this https://www.klgrth.io/paste/yj9ut but replacing the id with one of the activities i want to use

**Comment by riolubruh** [comment]
Thanks, I'll check it out when I can

**Comment by riolubruh** [comment]
I got it working through BD, but my Discord client has a tendency to crash when trying to start activities :/
Here's the code if you want to test it youself
![image](https://user-images.githubusercontent.com/54255074/202788494-092f5695-4c9d-45df-9b9d-b7060672bc11.png)

**Comment by riolubruh** [comment]
It sends a POST request when starting the activity, telling the server that you are in {X Guild ID}, {Channel ID}, and {User ID} and certain activities such as Chess/Checkers in the Park and many others will not work because the server sends an error.

**Comment by riolubruh** [comment]
nvm, I figured out how to just straight up make a custom activity
![sm64js](https://user-images.githubusercontent.com/54255074/203631652-ec0b0724-3d83-415e-afc3-4e2880f876a3.png)
![Chess](https://user-images.githubusercontent.com/54255074/203631791-e4a911c9-a4d5-4aaa-890a-e0203a5bbffc.png)
Although this is great and all, I kind of really need to get to fixing #37 and #36.

**Comment by riolubruh** [comment]
Amazing progress so far!
![Auto launch activity](https://user-images.githubusercontent.com/54255074/203650001-e7ec45b1-6c9e-47e3-be8e-b0889e0e5905.gif)
Now I just need to implement an elegant way for other others to join

**Comment by Pickymarker** [comment]
How do you do the custom activities like the super Mario 64 one what's the command and stuff to do it I'm just wondering so I can do I while I what for you to find a good way for people to join it

**Comment by riolubruh** [comment]
```js
let b = ZLibrary.WebpackModules.getByIndex(331792);
let c = b.Z._dispatcher;
c.dispatch({
	type: "DEVELOPER_TEST_MODE_AUTHORIZATION_SUCCESS",
	applicationId: "880218394199220334",
	originURL: "https://riolubruh.cf" //Or any custom URL, this is just an example
}); //After this code has run, it will overwrite the Watch Together activity
```

When the activity functionality in the plugin is complete, I'm planning to add the option for custom URLs.
In order to get sm64js to work, however, I had to manually disable the sandboxing on the iframe element with this code
```js
document.getElementsByClassName("iframe-2GuF98")[0].sandbox = "allow-downloads allow-forms allow-modals allow-orientation-lock allow-pointer-lock allow-popups allow-popups-to-escape-sandbox allow-presentation allow-same-origin allow-scripts allow-top-navigation allow-top-navigation-by-user-activation";
//Disable sandboxing features
document.getElementsByClassName("iframe-2GuF98")[0].src = document.getElementsByClassName("iframe-2GuF98")[0].src;
//Refresh to apply changes
```

**Comment by riolubruh** [comment]
It's ready! The GUI isn't that great, sorry; this is the best that I could do.

https://user-images.githubusercontent.com/54255074/204071848-ba593b6b-f002-4bb5-ae8e-331f66c437fc.mp4
