### ISSUE TITLE
how do you fix this 

### ISSUE THREAD

**Issue by Pickymarker** [riolubruh/YABDP4Nitro#36]
how do you fix this ![image](https://user-images.githubusercontent.com/74084396/201907709-8d856291-f57a-4a92-a04e-e218699fee3b.png)

**Comment by riolubruh** [comment]
I've never seen this before. Maybe an update to something can cause this to happen?
I'll see if I can recreate it

**Comment by Pickymarker** [comment]
this is the resolution and fps i get with theses settings in the config when i have it set to 900p and 120 fps and locked 3400 bitrate but i'm not getting that for some reason
![image](https://user-images.githubusercontent.com/74084396/202264094-1b458c78-c66d-48ba-808a-b5d02dc253c5.png)

**Comment by Pickymarker** [comment]
i got it to work but custom resolution just keeps saying source like this 
![image](https://user-images.githubusercontent.com/74084396/202275277-f2a50e7a-ca7b-4eff-8083-bf764bb9645a.png)

**Comment by riolubruh** [comment]
> i got it to work but custom resolution just keeps saying source like this and 60 but it should say 900p 120fps but when i screenshare it shows source 120 and i don't know if custom bitrate is working

The button no longer changes after the SWC update.
As for the resolution not going to the set value, I'm not sure why that's happening. Enable the resolution quick swapper and try to change the resolution from there.

**Comment by Pickymarker** [comment]
i tired that

**Comment by Pickymarker** [comment]
![image](https://user-images.githubusercontent.com/74084396/202308118-d53491a6-8275-49e5-80ce-7757f492269d.png)
![image](https://user-images.githubusercontent.com/74084396/202308126-91461535-6298-4145-ad7b-74319aba5570.png)
![image](https://user-images.githubusercontent.com/74084396/202308129-8820a75a-d1e2-46e7-9516-6d4c5575cf21.png)
![image](https://user-images.githubusercontent.com/74084396/202308172-b000ece4-a48f-4a42-9941-25eec4961998.png)

**Comment by Pickymarker** [comment]
Does the devtool console screenshots I sent help with figuring out what the problems is so that i can get it working

**Comment by riolubruh** [comment]
Picking the Source option seems to take priority now over the custom resolution and FPS. This means that in order to use the custom resolution, you actually have to pick 480/720/1080 instead. Here's an example of what I'm talking about.
![electron_ewIEStB9UW](https://user-images.githubusercontent.com/54255074/202594119-d5298d96-3985-47d3-a074-c4d673dad63d.gif)

**Comment by Pickymarker** [comment]
its fixed but after a certain amount of time it switches from custom fps back to 30fps

**Comment by riolubruh** [comment]
> how do you fix this ![image](https://user-images.githubusercontent.com/74084396/201907709-8d856291-f57a-4a92-a04e-e218699fee3b.png)
> 
> 

I've been able to recreate this on Arch Linux. Contact the creator of Zere's Plugin Library

**Comment by riolubruh** [comment]
Install the latest commit of ZeresPluginLibrary
[0PluginLibrary.plugin.zip](https://github.com/riolubruh/YABDP4Nitro/files/10078655/0PluginLibrary.plugin.zip)
