### ISSUE TITLE
Unable to modify emojisize

### ISSUE THREAD

**Issue by ny880202** [riolubruh/YABDP4Nitro#37]
am not a native speaker of English, please forgive me if I do not understand the grammar
I would like to ask whether the adjustment of the SIZE of EMOJI has not appeared in the selected interface is correct

[https://media.discordapp.net/attachments/1002587806419398686/1044910887997292575/image.png?width=514&height=559](url)

**Comment by riolubruh** [comment]
Please install the latest commit of 0PluginLibrary. I have linked a compiled version of the latest commit below.
[0PluginLibrary.plugin.zip](https://github.com/riolubruh/YABDP4Nitro/files/10078655/0PluginLibrary.plugin.zip)

**Comment by ny880202** [comment]
thx
