### ISSUE TITLE
this happening on spellcast 

### ISSUE THREAD

**Issue by Pickymarker** [riolubruh/YABDP4Nitro#39]
this happening on spellcast 
![image](https://user-images.githubusercontent.com/74084396/204076591-8358bd68-8aec-4a1b-82c0-fba4d92058ec.png)

**Comment by riolubruh** [comment]
Seems to work for me
![image](https://user-images.githubusercontent.com/54255074/204104587-1e060396-77c2-4c62-b73d-48986e929e79.png)

**Comment by Pickymarker** [comment]
fixed
