### ISSUE TITLE
Disabling Sticker Bypass Breaks Screen Share Options

### ISSUE THREAD

**Issue by majuula** [riolubruh/YABDP4Nitro#40]
When "Sticker Bypass" is toggled off, premium screen share options are no longer accessible.

![bruhh](https://user-images.githubusercontent.com/96037163/204083490-3ee3eb42-3fab-4829-b717-7e24fbbd996e.PNG)

Having the plugin enabled also breaks functionality for Nitro classic users: with sticker bypass disabled, I cannot use stickers as I normally could; with it enabled, a single sticker is instead sent 5 times.

**Comment by thiaguinho4** [comment]
The plugin has a problem that when it spends too much time active, it stops working, so almost that every time I go to use emotes or transmit the screen, I have to deactivate and activate again in the BetterDiscord settings. And this doesn't give any errors in the console.

**Comment by riolubruh** [comment]
woops lol, this is a dumb mistake on my part. it'll be fixed in a hotfix soon

**Comment by riolubruh** [comment]
I think this is fixed. If it still isn't working correctly, feel free to reopen the issue
