### ISSUE TITLE
Disabling Emoji Bypass Removes Nitro Emoji Functionality

### ISSUE THREAD

**Issue by majuula** [riolubruh/YABDP4Nitro#41]
I have Nitro Classic, but cannot use custom emojis normally when this plugin is enabled with the emoji bypass disabled.

![bruhh](https://user-images.githubusercontent.com/96037163/204118738-1a40a462-9553-4915-9ca1-cb5c96092349.PNG)

**Comment by DyonR** [comment]
Can confirm, I have the same issue

**Comment by riolubruh** [comment]
Shite, the issue is on line 448
```
if(!this.settings.emojiBypass){
```
Make it either `if(false){` or `if(!this.settings.emojiBypass && (this.originalNitroStatus >= 0))`

**Comment by riolubruh** [comment]
Reopen if the issue is not resolved in 4.3.2 / ee0608c
