### ISSUE TITLE
Stream Reactions Don't Work When Plugin Enabled

### ISSUE THREAD

**Issue by majuula** [riolubruh/YABDP4Nitro#43]
Users in a voice channel can react to streams using emojis that will pop up over their profile and on the side of the call:

![image](https://user-images.githubusercontent.com/96037163/204164646-8b27f713-08aa-49e4-9297-6414efa91c9a.png)

When the plugin is enabled, I'm unable to do so. The menu appears and icons seem to be interactable, but pressing them does nothing (both regular and nitro emojis).

**Comment by riolubruh** [comment]
honestly i didn't even know stream reactions worked at all or even existed

**Comment by majuula** [comment]
Yeah it's pretty niche, just noticed it haha

**Comment by Pickymarker** [comment]
the only emojis that don't work are the emoji bypass ones

**Comment by majuula** [comment]
Looks to be the case; I have nitro classic so I always have emoji bypass turned off — must’ve been reenabled when I updated the plugin.
