### ISSUE TITLE
Emoji Bypass Not Working after update

### ISSUE THREAD

**Issue by mobochi** [riolubruh/YABDP4Nitro#44]
After updating the plugin, it seems it got broken
No changes in settings from previous version.

Edit: Found a workaround that worked for me? i guess (it does work 1st try or need to do 3+ refresh/reload to work)
1. I turned off all of Settings under **Emoji**
2. reloaded/refreshed discord
3. then turned back on the settings under **Emoji** settings

**Comment by riolubruh** [comment]
Can you be more specific about what's happening?

The only thing that should have changed relating to emojis is the function that checks if an emoji is unlocked or is from the same server that you are sending it in

**Comment by mobochi** [comment]
Found the issue!

It seems that if the "Sticker Bypass" is turned on in Emoji settings upon the launch of Discord it'll cause the bug which you can't use Emojis that needs Nitro. as shown here.
![image](https://user-images.githubusercontent.com/77446356/204222401-3d8a6725-31f2-4867-9a62-5b11a89c0644.png)
![image](https://user-images.githubusercontent.com/77446356/204222303-75abeccb-16da-46ff-9c68-81f9695fe413.png)

Once I turn it off, the Emojis will work as intended.
![image](https://user-images.githubusercontent.com/77446356/204222609-d3923d5f-5266-42b9-9f71-563049659c05.png)
![image](https://user-images.githubusercontent.com/77446356/204222834-5af66929-8195-4289-b733-701d0bbdf985.png)

Once the Emoji Bypass already worked once during the Discord Session turning on/off/on the Sticker Bypass won't affect Emojis Bypass (Emojis will stay useable), just don't reload/restart the Discord with Sticker Bypass Settings turned ON.

**Comment by surya27895** [comment]
had same issue, but mobochi workaround still not works for me

**Comment by riolubruh** [comment]
Will check it out later today. Sorry about accidentally causing stupid issues like this, there's a lot of different options in the plugin that sometimes conflict

**Comment by riolubruh** [comment]
Can't test it right now cause I don't have my pc, see if this version works
https://github.com/riolubruh/YABDP4Nitro/blob/permissions-fix-attempt/YABDP4Nitro.plugin.js

**Comment by surya27895** [comment]
> Can't test it right now cause I don't have access to my pc, see if this version works https://github.com/riolubruh/YABDP4Nitro/blob/permissions-fix-attempt/YABDP4Nitro.plugin.js

still no luck , i guess
![image](https://user-images.githubusercontent.com/22859567/204342329-1279babd-41ef-454d-b6e5-ffc110f4aca5.png)

**Comment by riolubruh** [comment]
Can you upload the config file so it's easier for me to see what options may be causing the issue?

**Comment by surya27895** [comment]
this config? sorry if I attach wrong file
[YABDP4Nitro.config.zip](https://github.com/riolubruh/YABDP4Nitro/files/10106190/YABDP4Nitro.config.zip)

**Comment by riolubruh** [comment]
yeah. check new version in the branch

**Comment by surya27895** [comment]
still can get it works

here what I do so far...
- downgrading plugins ✅
- instal use zeresplugins from this repo ✅
- instal use zeresplugins from original repo ✅
- delete plugins and config > instal > reload ✅
- delete plugins and config > instal > restart ✅
- remove as much as possible plugins to avoid plugins conflict (attached below) ✅
use![image](https://user-images.githubusercontent.com/22859567/204350296-429ef4cf-a625-4781-b806-bec28218dd8b.png)

**Comment by riolubruh** [comment]
I cannot reproduce the bug on my system, even with an identical config. Would like some more information if possible, many any errors in DevTools after the plugin loads, or something like that.

**Comment by riolubruh** [comment]
Stale issue, possible duplicate
