### ISSUE TITLE
SoyRage is still stealing the plugin and also he has a website and a youtube channel

### ISSUE THREAD

**Issue by Pickymarker** [riolubruh/YABDP4Nitro#45]
https://github.com/SoyRage/ImNitro is still stealing the plugin and claiming it as his and also he has a website https://soyrage.es/contact and a youtube channel https://www.youtube.com/@SoyRage with 76k but no videos public

**Comment by riolubruh** [comment]
I know and I'm fucking annoyed because I initially made him private the repo and then he turned around and unprivated it shortly after

**Comment by riolubruh** [comment]
I'm once again talking to him. [I created a pull request for him](https://github.com/SoyRage/ImNitro/pull/3) to just follow the god damn [license](https://github.com/riolubruh/YABDP4Nitro/blob/main/LICENSE.md) so I can finally stop having to deal with talking to soyboy.

**Comment by riolubruh** [comment]
![image](https://user-images.githubusercontent.com/54255074/204433024-d905bdd0-995d-48c8-a423-5323af239b0e.png)
