### ISSUE TITLE
Animated StickersBypass Not Working 

### ISSUE THREAD

**Issue by EngineExt** [riolubruh/YABDP4Nitro#46]
![2022-11-28_14-06-44](https://user-images.githubusercontent.com/28253387/204263142-d6b125b4-2f51-44d4-88e4-6f51c6d3fb65.gif)
The animated sticker is sent as a regular image in png format

![image](https://user-images.githubusercontent.com/28253387/204263508-d114aaff-09e6-467a-a190-ae4a0f04d92b.png)

**Comment by EngineExt** [comment]
> Currently this is intended, I haven't been able to convert the APNG to GIF :/ I tried using apng.js and canvas2gif with no success

Perhaps you will be "inspired" by the working version from An00nymushun https://raw.githubusercontent.com/An00nymushun/DiscordFreeStickers/main/FreeStickers.plugin.js

**Comment by riolubruh** [comment]
I already kind of tried looking through FreeStickers as a sort of guide, but I don't think it's even necessary to mention that FreeStickers is extremely complicated and the code is _incredibly_ difficult for me to understand. Not to mention it's very high file size and it's [license](https://github.com/An00nymushun/DiscordFreeStickers/blob/main/LICENSE) is fairly restrictive so I don't want to use his code 1:1 in my plugin if I can avoid it.

**Comment by riolubruh** [comment]
Also this plugin used to have perfect compatibility with FreeStickers but I stopped focusing on it because An0's plugin was broken for a long time

**Comment by riolubruh** [comment]
Compatibility with FreeStickers has been restored. Just use this plugin with FreeStickers.

**Comment by riolubruh** [comment]
Closing this issue because I have no plans to add support for **animated** Stickers.
