### ISSUE TITLE
i get this error when using the plugin on latest version 

### ISSUE THREAD

**Issue by Pickymarker** [riolubruh/YABDP4Nitro#49]
i get this error when using the plugin on latest version  
![image](https://user-images.githubusercontent.com/74084396/204415436-c2159db6-8fe9-4461-a6a0-ced6a737f062.png)

**Comment by thiaguinho4** [comment]
same
![1](https://user-images.githubusercontent.com/101910294/204421493-fa82d5d1-2c63-4581-959d-61d1577a3673.png)

**Comment by Pickymarker** [comment]
i'm wondering what's causing this

**Comment by riolubruh** [comment]
i accidentally left some unfinished code in the latest commit
