### ISSUE TITLE
Reply is lost when uploading an emote

### ISSUE THREAD

**Issue by BlackusPL** [riolubruh/YABDP4Nitro#5]
This plugin messes up replying to messages

**Comment by riolubruh** [comment]
Okay! I'll try my best to fix it
By the way, this only happens when uploading is enabled. If you need replies, for now your best option is to disable uploading cause it was just added and can be buggy still

**Comment by riolubruh** [comment]
Partially fixed. Now only happens when you actually upload an emote, instead of any time "Upload Emotes" is enabled.

**Comment by riolubruh** [comment]
Don't think this is possible to fix.
