### ISSUE TITLE
Emoji Bypass Not Working after Commits on Nov 28, 2022

### ISSUE THREAD

**Issue by EngineExt** [riolubruh/YABDP4Nitro#50]
All emojis are sent like this → 
![image](https://user-images.githubusercontent.com/28253387/204464399-aedde7fe-d434-4240-b672-f8e152facf0c.png)
I rolled back the plugin version to [4.3.2](https://github.com/riolubruh/YABDP4Nitro/blob/ee0608cff2c8aefdc9e7c7704b7f5719c76da634/YABDP4Nitro.plugin.js), where I found out when it was broken.
P.S After this fix #47  It's broken

**Comment by FerLuisxd** [comment]
I literally have this same issue since the last update

**Comment by FerLuisxd** [comment]
![image](https://user-images.githubusercontent.com/29811965/204577304-f2ad2478-31eb-4106-beba-e1ac5cac4890.png)
This is the emoji config for the plugin

**Comment by riolubruh** [comment]
Make sure you have the latest version. If you've done that already, the way I see it there are 3 possibilities:
1. emoji bypass is just not running (which could be either because it's disabled or an error occurs before it can run)
2. It could think the emojis are already unlocked (see emojiBypassForValidEmoji)
3. Something somewhere could be written incorrectly preventing emojibypass from working correctly (very possible, although not very helpful.)

Close BD, delete plugin and install the latest version of the plugin and its dependencies, then open up Console/DevTools (Google it if you don't know how) and then enable the plugin. If any errors are spit out during plugin load or while attempting to use its features, put them here

**Comment by riolubruh** [comment]
> ![image](https://user-images.githubusercontent.com/29811965/204577304-f2ad2478-31eb-4106-beba-e1ac5cac4890.png)
> 
> This is the emoji config for the plugin

Something about this looks odd. Make sure you have the newest compiled version of 0PluginLibrary (you can find it in this repo)

**Comment by EngineExt** [comment]
1. I have newest compiled version of 0PluginLibrary.
2. https://youtu.be/D8lL3zbRp5U - DevTools is empty
3. My config
```{
    "currentVersionInfo": {
        "version": "4.3.4",
        "hasShownChangelog": true
    },
    "settings": {
        "emojiSize": 80,
        "screenSharing": true,
        "emojiBypass": true,
        "ghostMode": true,
        "emojiBypassForValidEmoji": true,
        "PNGemote": true,
        "uploadEmotes": false,
        "CustomFPSEnabled": false,
        "CustomFPS": 75,
        "ResolutionEnabled": false,
        "CustomResolution": 0,
        "CustomBitrateEnabled": false,
        "minBitrate": -1,
        "maxBitrate": -1,
        "targetBitrate": -1,
        "voiceBitrate": 128,
        "audioSourcePID": 0,
        "CameraSettingsEnabled": false,
        "CameraWidth": 1920,
        "CameraHeight": 1080,
        "ResolutionSwapper": false,
        "stickerBypass": false,
        "profileV2": true,
        "activityJoiningMode": false,
        "activityBypass": true,
        "customActivityURL": "",
        "customActivity": false
    }
}

**Comment by riolubruh** [comment]
I can't work on the plugin until later, but oh shit! Watching the video, I think I recognize the problem! Earlier in the plugin's life, there was an issue where the plugin would compare the _last server_ you were looking at with _the server that the emoji is from_ and there was a bug that only applied to DMs where if the last server you viewed was the same as the emote's origin it would decide not to use the bypass.
>It could think the emojis are already unlocked (see emojiBypassForValidEmoji)
>

Judging from your config, emojiBypassForValidEmoji is enabled and if my hunch is correct, then disabling it (setting it to false) should make it work. I was recently changing this function to have its old behavior, but I may have missed the part where I check if it's a DM

**Comment by EngineExt** [comment]
> Judging from your config, emojiBypassForValidEmoji is enabled and if my hunch is correct, then disabling it (setting it to false) should make it work. I was recently changing this function to have its old behavior, but I may have missed something.

It didn't help.

**Comment by riolubruh** [comment]
I'll begin work on this issue in #53 later today when I can test it

**Comment by riolubruh** [comment]
> > Judging from your config, emojiBypassForValidEmoji is enabled and if my hunch is correct, then disabling it (setting it to false) should make it work. I was recently changing this function to have its old behavior, but I may have missed something.
> 
> It didn't help.

It shouldn't considering I just noticed that I forgot to move the if(this.settings.emojiBypassForValidEmoji) statement in the emojiBypassForValidEmoji function  -_-

**Comment by riolubruh** [comment]
I think I am officially an idiot. The issue was caused by a single **character.**
uploading newest version

**Comment by EngineExt** [comment]
Broke it again In 4.3.6
