### ISSUE TITLE
Unable to type values in options

### ISSUE THREAD

**Issue by BlackusPL** [riolubruh/YABDP4Nitro#51]
You cant type values to Custom Screenshare FPS, Resolution, Bitrate, Camera and Custom Activities.
![image](https://user-images.githubusercontent.com/45206560/204491311-49248044-b112-462d-b39b-54221f73884c.png)

**Comment by BlackusPL** [comment]
Solution for now is editing YABDP4Nitro.config.json to change values

**Comment by riolubruh** [comment]
See #36

**Comment by BlackusPL** [comment]
now works, thx
