### ISSUE TITLE
META not found error when starting of discord

### ISSUE THREAD

**Issue by yushen-tok** [riolubruh/YABDP4Nitro#55]
discord gives a META not found error when I start discord.

I already have the latest version of the 0lib v2.0.9
<img width="545" alt="Screenshot 2022-12-02 at 6 31 04 PM" src="https://user-images.githubusercontent.com/113019855/205273333-7d1cf1d2-a42c-4614-879d-02ad2918fbc2.png">

**Comment by JonasBBX** [comment]
Happened to me once or twice just delete the plugin and redownload it from github and get a fresh copy don't use any old one

**Comment by riolubruh** [comment]
Indeed. It can happen seemingly randomly to any plugin. It usually happens from corruption of the plugin file, and not due to a programming error.
