### ISSUE TITLE
emotes and gif emotes not sending as links

### ISSUE THREAD

**Issue by yushen-tok** [riolubruh/YABDP4Nitro#57]
I have tried to send emotes from other servers (both static and animated, the emotes display even as it is being uploaded, but returns back to text with colons (ie :welcome:) after it sends. However, when I click to edit the message, the emote displays as it should. Sending animated stickers does work as intended, as gifs (however that could be due to the freestickers plugin) 

when sending:
<img width="98" alt="Screenshot 2022-12-02 at 11 09 58 PM" src="https://user-images.githubusercontent.com/113019855/205324121-7f5db268-f78b-4788-bcc6-12f510d3647b.png">

after sent:
<img width="83" alt="Screenshot 2022-12-02 at 11 10 06 PM" src="https://user-images.githubusercontent.com/113019855/205324149-06e0c5a4-ffed-493f-965f-0386c02cf459.png">

when editing:
<img width="173" alt="Screenshot 2022-12-02 at 11 11 44 PM" src="https://user-images.githubusercontent.com/113019855/205324785-4e166b4b-b9f3-4215-8da3-8da6b934c0be.png">

These are my configs for the plugin:
<img width="575" alt="Screenshot 2022-12-02 at 11 12 42 PM" src="https://user-images.githubusercontent.com/113019855/205324673-2a631b2d-44f6-47c3-b236-649b244f5da3.png">
<img width="575" alt="Screenshot 2022-12-02 at 11 12 50 PM" src="https://user-images.githubusercontent.com/113019855/205324713-e954b48b-edfb-4105-b887-7d49289662e2.png">

versions of the plugins (fresh install off GitHub):
<img width="665" alt="Screenshot 2022-12-02 at 11 15 18 PM" src="https://user-images.githubusercontent.com/113019855/205325058-b727e5c2-b3a8-48e3-93ee-5070fb436a27.png">

I have checked to remove or disable any conflicting emotes plugin I have so im confused as to why this happens.

**Comment by EngineExt** [comment]
#50 Again...

**Comment by FerLuisxd** [comment]
Same to me...

**Comment by riolubruh** [comment]
Reinstalled Discord and this bug appears. Fuck

**Comment by riolubruh** [comment]
I'm just going to remove the isEmojiFilteredOrLocked check. It doesn't seem to ever work consistently, no matter what I do.
