### ISSUE TITLE
Where do I find the setting to change camera resolution?

### ISSUE THREAD

**Issue by CrimsonCuttle** [riolubruh/YABDP4Nitro#60]
The screenshot provides no context for where to find the setting.
Also cannot find out how to change stream bitrate.

**Comment by riolubruh** [comment]
Are you blind
![camera](https://user-images.githubusercontent.com/54255074/206576184-7ff874a2-3716-47e6-ba12-b02c2e1fba4c.png)
bitrate is under Screen Share Features.
Make sure you have the latest version of BD and ZeresPluginLibrary/0PluginLibrary
