### ISSUE TITLE
Cannot choose emotes that are locked due to Server Boost Level dropping

### ISSUE THREAD

**Issue by ascv0228** [riolubruh/YABDP4Nitro#64]
![image](https://user-images.githubusercontent.com/77038091/208241445-a2fbe788-8be1-4b9e-a1a8-13a242bf87ff.png)

emoji cannot choose because the server's premiumTier reduce.

**Comment by riolubruh** [comment]
?

**Comment by ascv0228** [comment]
![image](https://user-images.githubusercontent.com/77038091/208453831-953a9003-9125-441b-84ff-435149db5e8c.png)
the emojis behind the red line in the picture cannot be chosen because the server boost tier reduced from level 1 to no boosts. 

![image](https://user-images.githubusercontent.com/77038091/208454728-f7d43283-3ff7-48c5-b479-cdf239a7ac5b.png)
level 1 have a bonus "unlocked 50 emojis slots". if the server boost tier decrease, this 50 emojis slots will locked, so i cannot choose them.

**Comment by riolubruh** [comment]
Ohh. This is related to the server's boost status, not the user's Nitro status. This is not a mistake on the plugin's side, maybe you would consider it a possible feature?
You could just create another server and upload the emotes to the free slots there as a workaround.

**Comment by riolubruh** [comment]
Woops, I think this was unintentionally added lol.
