### ISSUE TITLE
Screen Share Audio Source doesn't work

### ISSUE THREAD

**Issue by ktt45678** [riolubruh/YABDP4Nitro#66]
I tried to set the Screen Sharing Audio Source to the PID of the app that I need to stream the audio from, but the stream audio is still coming from the screen sharing app instead of the app with selected PID.
I also tried to change quality and window a few times, but it doesn't seem to solve the issue.

**Comment by riolubruh** [comment]
I modified the code of the audio share module but I don't think it's fixed yet so I'm keeping this open

**Comment by ktt45678** [comment]
It's not fixed. However when I try to stream the File Explorer screen (Windows 10), somehow it works as expected. This only happens with the File Explorer app.

**Comment by Pickymarker** [comment]
yeah same happens for me that screen share source audio does not work and i tried multiple pids from tasklist that work normally.

**Comment by Pickymarker** [comment]
when is this going to be fixed @riolubruh

**Comment by riolubruh** [comment]
> when is this going to be fixed @riolubruh

When I figure out what's wrong™

**Comment by Pickymarker** [comment]
okay once its fixed can you make it similar to the better discord screen share plugin so we don't have to guess what number is for what app because sometimes app have multiple process which each have a different number

**Comment by Pickymarker** [comment]
has there been any progress on a fix for this

**Comment by riolubruh** [comment]
> has there been any progress on a fix for this

Unfortunately not. It should probably be removed at this point, honestly :/

**Comment by Pickymarker** [comment]
But how does better discord screenshare in vencord by philhk have it working without needing audio source number perfectly

**Comment by riolubruh** [comment]
> But how does better discord screenshare in vencord by philhk have it working without needing audio source number perfectly

Idk man lol I'm not him

**Comment by Eden333** [comment]
> But how does better discord screenshare in vencord by philhk have it working without needing audio source number perfectly

probably because they're using their own version of a similar working plugin
https://github.com/philhk/better-discord-screenshare-plugin

**Comment by riolubruh** [comment]
Removed in 4.5.4 (281eafd).
