### ISSUE TITLE
Cannot expand settings

### ISSUE THREAD

**Issue by Apoc101** [riolubruh/YABDP4Nitro#67]
Hi, expanding on the settings tab of the plugin does nothing, even with 0 themes and no other plugins. 

![image](https://user-images.githubusercontent.com/87915954/216797923-bd15c363-b2bd-4306-933c-8c7a2adcd2eb.png)

**Comment by riolubruh** [comment]
You **must** have Zere's Plugin Library installed for this plugin to function.

**Comment by 945661426** [comment]
> You **must** have Zere's Plugin Library installed for this plugin to function.

<img width="1090" alt="Screenshot_20230207_022047" src="https://user-images.githubusercontent.com/69743306/217053667-e644d29f-e65d-4b12-b618-ec4dc82017c1.png">
<img width="352" alt="Screenshot_20230207_022059" src="https://user-images.githubusercontent.com/69743306/217053676-16ed3839-b007-4ce6-8b3c-96cca39c7a75.png">

**Comment by 945661426** [comment]
<img width="487" alt="Screenshot_20230207_022208" src="https://user-images.githubusercontent.com/69743306/217053791-068f7960-8a3b-4a86-9690-ff0b97c2fb0f.png">

**Comment by 945661426** [comment]
It's not expanding for me either

**Comment by 945661426** [comment]
<img width="136" alt="Screenshot_20230207_023617" src="https://user-images.githubusercontent.com/69743306/217056564-88972b8f-ed01-487b-9f27-5141d06e47a6.png">
After downloading the newest version of 0pluginlibrary it's working now

**Comment by riolubruh** [comment]
Please install the latest version of Zere's Plugin Library
