### ISSUE TITLE
Custom FPS + Settings not saving after restart/closing

### ISSUE THREAD

**Issue by Hexishu** [riolubruh/YABDP4Nitro#72]
Just as I stated, trying to set a custom fps e.g. 240 fps doesn't work, unloaded, reinstalled plugins multiple times, only showing 60 fps at max

**Comment by riolubruh** [comment]
Please send your config file

**Comment by riolubruh** [comment]
>empty
That ain't right... you might want to reinstall BetterDiscord or something
