### ISSUE TITLE
Error: META was not found

### ISSUE THREAD

**Issue by Neipas09** [riolubruh/YABDP4Nitro#74]
I get the following error when adding the .js file to the plugins folder.
![image](https://user-images.githubusercontent.com/58871039/221391364-c441ac3d-5785-44eb-9638-149e1cbad870.png)

[META error.txt](https://github.com/riolubruh/YABDP4Nitro/files/10832912/META.error.txt)

**Comment by riolubruh** [comment]
Duplicate of #73
