### ISSUE TITLE
add F.A.Q. for people who don't often use github

### ISSUE THREAD

**Issue by sad-cactus** [riolubruh/YABDP4Nitro#75]
me being one of these people, it would certainly help to add an F.A.Q. as i had some questions about this plugin, i had to search and only found answers [here](https://github.com/riolubruh/YABDP4Nitro/issues/58)

**Comment by riolubruh** [comment]
Sure

**Comment by riolubruh** [comment]
Added it. If you want anything else added to the FAQ, comment it under that issue.
