### ISSUE TITLE
Frequently Asked Questions (FAQ)

### ISSUE THREAD

**Issue by riolubruh** [riolubruh/YABDP4Nitro#76]
**Q: Will I get banned for using this plugin?**
**A:** As of now, as far as I know nobody has been banned for using this plugin. However, you must always keep in mind that client modifications such as BetterDiscord are technically against Discord's Terms of Service, meaning that technically you can be banned for using BetterDiscord. 
However, this happening has proven to be extremely uncommon and usually only happens if you are 1) Spamming the API, 2) reported, or 3) self-botting.

**Q: Can Discord detect when someone is using plugins like this?**
**A:** It is technically possible for Discord to implement detection for certain features of the plugin, such as high quality screen share. However, Discord hasn't done it, so it is safe to assume that they don't really care that much.
Furthermore, many of the plugin's features would not be detectable anyways (such as emoji) because you can do a few of the things that this plugin does yourself as well. This plugin also does not interact with any APIs that a user would not be able to access themself. 

**Q: Does this plugin actually give you Nitro?**
**A:** Short answer: **No.**
Long answer: This plugin does several things; either 'emulating' or just straight up unlocking _specific_ Nitro features. The Nitro features that it "unlocks" are all things that are client-side. For instance, the screen share quality is basically entirely handled by the _client_ and not the _server._ I go through great lengths to avoid interacting with the server in any way that is not necessary.
Furthermore, it is impossible to give an account Nitro on the server-side without paying, and even if it was somehow possible you would definitely be banned for doing so (and it would probably be patched very quickly).

**Q: I am getting a "META Not Found" error!! Can you fix it?**
**A:** This is almost always not an issue of the plugin, and is most likely caused by plugin file corruption.
Deleting and redownloading the plugin should fix the error. 
If you make an issue about "META Not Found", I will laugh at you (unless it actually is a widespread issue)

**Q: Can you add [this] to the FAQ?**
**A:** Comment it below and I will consider adding it.

**Comment by Maverynthia** [comment]
Add to FAQ: How do I undo profile modifications?

**Comment by riolubruh** [comment]
> Add to FAQ: How do I undo profile modifications?

Clear out the 3y3 from your status and bio. Easiest way to do so is to just completely delete your bio and status, but if you know where you pasted them, you can just delete them that way.

**Comment by asidem** [comment]
Add this to FAQ too: Can you add this plugin to betterdiscord?

**Comment by riolubruh** [comment]
> Can you add this plugin to betterdiscord?

It... it _is_ a BetterDiscord plugin... I'm assuming you meant another client mod like Vencord though.

**Comment by baldi2** [comment]
Add this to FAQ: how do i giev myself nitro badge

**Comment by asidem** [comment]
> > Can you add this plugin to betterdiscord?
> 
> It... it _is_ a BetterDiscord plugin... I'm assuming you meant another client mod like Vencord though. I'll add it.

I mean inside of the betterdiscord's web site, https://betterdiscord.app/plugins

**Comment by riolubruh** [comment]
> > > Can you add this plugin to betterdiscord?
> 
> > 
> 
> > It... it _is_ a BetterDiscord plugin... I'm assuming you meant another client mod like Vencord though. I'll add it.
> 
> 
> 
> I mean inside of the betterdiscord's web site, https://betterdiscord.app/plugins

"Will this plugin be added to the BetterDiscord website?" is already a question.

**Comment by riolubruh** [comment]
> Add this to FAQ: how do i giev myself nitro badge

you're the first to ask that

**Comment by baldi2** [comment]
> > Add this to FAQ: how do i giev myself nitro badge
> 
> you're the first to ask that. you can't.

a friend of mi negave me this plugin code with nitro badges

**Comment by riolubruh** [comment]
> > > Add this to FAQ: how do i giev myself nitro badge
> > 
> > 
> > you're the first to ask that. you can't.
> 
> a friend of mi negave me this plugin code with nitro badges

when I said you can't, I meant that you can't with the regular version of the plugin. it's possible to add a nitro badge to your profile on the client side, but nobody else will see it unless they also have a modified version of the plugin. the plugin does give every user who uses yabdp4nitro's fake profile features a unique badge, though, which I think is nicer than the normal nitro badge

**Comment by Litchlol** [comment]
How do i change the bitrate for streaming?

if i go to screen share, the only options i have are resolution and FPS, neither of them are custom.

**Comment by riolubruh** [comment]
> How do i change the bitrate for streaming?
> 
> if i go to screen share, the only options i have are resolution and FPS, neither of them are custom.

@Litchlol 
Under the Screen Share Features category, you should see these textboxes where you can change the resolution and FPS if you scroll down. If these do not appear, then it's a bug, so please get in contact!

![Discord_5m6DcslJVu](https://github.com/riolubruh/YABDP4Nitro/assets/54255074/4240f0fc-902b-4c8b-ac59-cd10c9270faa)
![Discord_wV7b8u7ijj](https://github.com/riolubruh/YABDP4Nitro/assets/54255074/dbe2f1fc-f72d-45ad-8bf9-10a8917a0bcc)

**Comment by Litchlol** [comment]
> > How do i change the bitrate for streaming?
> > if i go to screen share, the only options i have are resolution and FPS, neither of them are custom.
> 
> @Litchlol Under the Screen Share Features category, you should see these textboxes where you can change the resolution and FPS if you scroll down. If these do not appear, then it's a bug, so please get in contact!
> 
> ![Discord_5m6DcslJVu](https://private-user-images.githubusercontent.com/54255074/296042855-4240f0fc-902b-4c8b-ac59-cd10c9270faa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwMDU3OTMsIm5iZiI6MTcwNTAwNTQ5MywicGF0aCI6Ii81NDI1NTA3NC8yOTYwNDI4NTUtNDI0MGYwZmMtOTAyYi00YzhiLWFjNTktY2QxMGM5MjcwZmFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTExVDIwMzgxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0YjAxMjY1NjFmNDFmYTBlMjA4OTY2ZTg4YTM2NGZlM2ZjY2NkY2VjYjRlZDcwYTU4ZTA2YWEwNDNhZTkxNTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rqI6wZ710fHblaMwwsovIc3O-7SyQ35MC6ullVkmMCw) ![Discord_wV7b8u7ijj](https://private-user-images.githubusercontent.com/54255074/296042860-dbe2f1fc-f72d-45ad-8bf9-10a8917a0bcc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwMDU3OTMsIm5iZiI6MTcwNTAwNTQ5MywicGF0aCI6Ii81NDI1NTA3NC8yOTYwNDI4NjAtZGJlMmYxZmMtZjcyZC00NWFkLThiZjktMTBhODkxN2EwYmNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTExVDIwMzgxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5NDg2MWM1OWU1NGYyZjNiZmZhMjdmM2JkM2MxNjQ1MWVlYmI5NGJmZGE0NmQzYTVmYzA5OGM2MzFlMTQyZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Yy4JoK4EVsmD_0IuUlXXalkrw8OFcCAfZ8X_jMASUHw)

Sorry if i'm being dumb, but where exactly is said "Screen Share Features Catagory"

**Comment by Litchlol** [comment]
ignore last message, didnt see the gear next to the plugins themselves, sorry very new to better discord

**Comment by geeflaxx** [comment]
how you guys know when you should update this plugin?

**Comment by riolubruh** [comment]
> how you guys know when you should update this plugin?

?

**Comment by Maverynthia** [comment]
> how you guys know when you should update this plugin?

It will popup in discord to update

**Comment by Alex-Artemiev** [comment]
Hey, I have a problem with the plugin. The options to customize the server profile exist, but are covered by the nitro banner
![image](https://github.com/riolubruh/YABDP4Nitro/assets/166042898/0d66bf87-059a-43d2-9835-fe4f623cd170)

**Comment by riolubruh** [comment]
> Hey, I have a problem with the plugin. The options to customize the server profile exist, but are covered by the nitro banner
> 
> ![image](https://github.com/riolubruh/YABDP4Nitro/assets/166042898/0d66bf87-059a-43d2-9835-fe4f623cd170)
> 
> 

@Alex-Artemiev this is normal. You currently cannot use Nitro profile customization on a server-by-server basis.

**Comment by HITARI323** [comment]
Hi, I'm using GOOGLE Translate. The screenshots are the parameters, computer equipment and network I set. I bought Nitro, but the quality of the share screen has never been high. After using your plug-in, it worked normally until 6/28. The sound is normal but the picture starts to freeze. I wonder if it is related to disharmony? Or a plug-in? I checked with my internet provider and they said the line was fine. Thanks.
I wonder if there will be a chance to add AV1/VP9 to the video encoding part in the future?
![擷取280](https://github.com/riolubruh/YABDP4Nitro/assets/174807483/7af16a89-c98b-4bbb-8004-6585f93a78c9)
![擷取281](https://github.com/riolubruh/YABDP4Nitro/assets/174807483/e9a4f499-29d5-44aa-abe5-55ccb28dd279)

**Comment by riolubruh** [comment]
@HITARI323 It is possible that you could be putting too much stress on Discord's servers. Your minimum bitrate is much higher than what Discord normally supports, so I would try lowering that first.

**Comment by HITARI323** [comment]
> @HITARI323您可能對 Discord 的伺服器施加了太大的壓力。您的最低比特率遠高於 Discord 通常支援的比特率，因此我會先嘗試降低該位元率。
So what is the lowest bitrate you recommend setting? Mainly use 1080P60 or 2160P30. Thank you.

**Comment by InspiringOwl44** [comment]
Is there a way to add the Entrance Sound feature to the plugin?

**Comment by mgt1309** [comment]
Is there an option to unlock the emoji from any server to use as reactions? I seen something similar implemented in an aliucord plugin. It was only non-animated emojis that would work.

**Comment by riolubruh** [comment]
> Is there an option to unlock the emoji from any server to use as reactions? I seen something similar implemented in an aliucord plugin. It was only non-animated emojis that would work.

@mgt1309 
This feature does not exist.
I have heard people talk about this shiny Pokemon of a Aliucord plugin supposedly existing, but I have never actually seen proof of such a thing ever existing.
It should be entirely impossible to do this without some kind of bot or external API since the Discord API rejects it.

**Comment by HITARI323** [comment]
Hello,

First of all, thank you for developing this BT plugin. I have been using it for about eight months, and I truly appreciate it.

I have a question regarding a recent issue: when using the plugin and enabling screen sharing, everything works fine if the shared screen is in windowed mode. However, if I switch to fullscreen, the colors appear abnormal. Is this a known issue?

Thank you!

For reference, if I don’t use the plugin, fullscreen mode displays correctly. I have attached a screenshot:

The top screenshot shows windowed mode with the plugin enabled.
The middle screenshot shows fullscreen mode with the plugin enabled.
The bottom screenshot shows fullscreen mode without the plugin.

All streaming platforms and media players exhibit the same [issue.[](url)](url)

![Image](https://github.com/user-attachments/assets/97e20b27-3068-4e66-8fb8-c2e3a23be978)

![Image](https://github.com/user-attachments/assets/ae61636c-9dc5-4616-9105-fd9e67f7b13b)

![Image](https://github.com/user-attachments/assets/73676f80-a4b7-4f19-9014-11c9bd05a2c2)

**Comment by rage-more** [comment]
**[Question]** Does this allow for Webcams to be 60 FPS? trying to use it for Virtual OBS but it still Outputs as the default 30. Unsure if its only for streaming.

**Comment by Entity7** [comment]
Won't let me upload longer videos
I checked in plugin settings and its on
When I upload a file it still does the nitro ad and doesn't upload the file (The file is 36 MB)

**Comment by riolubruh** [comment]
@Entity7 add me on discord

**Comment by riolubruh** [comment]
> **[Question]** Does this allow for Webcams to be 60 FPS? trying to use it for Virtual OBS but it still Outputs as the default 30. Unsure if its only for streaming.

@rage-more not right now

**Comment by modraws** [comment]
really stupid edgecase but yeah. i am already a nitro user, but i have certain use-cases in which it's better for me to use bypassed emojis and stickers for embedding reasons. would it be possible for you to add an entry to the right-click menu in the emoji/sticker picker pop-up? to perhaps copy the link to the emoji or sticker, which i can then manually paste into my messages?

**Comment by riolubruh** [comment]
> really stupid edgecase but yeah. i am already a nitro user, but i have certain use-cases in which it's better for me to use bypassed emojis and stickers for embedding reasons. would it be possible for you to add an entry to the right-click menu in the emoji/sticker picker pop-up? to perhaps copy the link to the emoji or sticker, which i can then manually paste into my messages?

@modraws Good idea. I'd also thought about adding it before, I'm glad to see there's at least one other person who would appreciate that addition.

**Comment by FinixEz** [comment]
can you possible make steam quality frame rate to be able to adjust like remove 15 fps and keep 30 60 180 etc... because sometime game require too much gpu and every it happen i need to turn down or off custom fps and it might improve user experience.

<img width="453" height="465" alt="Image" src="https://github.com/user-attachments/assets/ee36bb06-8146-4c48-84ac-0730d44ca9df" />

**Comment by chadodark-ux** [comment]
i have a problem regarding the plugin
this image is shown to me and i cant enable the plugin

<img width="706" height="243" alt="Image" src="https://github.com/user-attachments/assets/7370d70d-2724-4ef9-b0bd-e7c68c108da2" />

**Comment by riolubruh** [comment]
> i have a problem regarding the plugin this image is shown to me and i cant enable the plugin
> <img alt="Image" width="706" height="243" src="https://private-user-images.githubusercontent.com/272871467/572605742-7370d70d-2724-4ef9-b0bd-e7c68c108da2.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzU1MzA5MDksIm5iZiI6MTc3NTUzMDYwOSwicGF0aCI6Ii8yNzI4NzE0NjcvNTcyNjA1NzQyLTczNzBkNzBkLTI3MjQtNGVmOS1iMGJkLWU3YzY4YzEwOGRhMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwNDA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDQwN1QwMjU2NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ODI2N2U2YjkyODkxOGI0YjVhMDdmNTFiYTkzYzk3OWFkZjcyMTRiNGRiZTg4M2M0YjkyZDdmNjBkYTZkMjk4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.H6yyfwwWExF7foVHyDxvYdWI417f68J0n-S7_LqVmbQ">

@chadodark-ux i cant tell if this is meant to be a joke but i laughed regardless cause bro where did you even find that? anyways just in case you were actually serious, that's not even a version of this plugin, so uh maybe try downloading [this plugin](https://riolubruh.github.io/autoDownload/?file=https://raw.githubusercontent.com/riolubruh/YABDP4Nitro/main/YABDP4Nitro.plugin.js)..?

**Comment by xFrxdx** [comment]
> > i have a problem regarding the plugin this image is shown to me and i cant enable the plugin
> > <img alt="Image" width="706" height="243" src="https://private-user-images.githubusercontent.com/272871467/572605742-7370d70d-2724-4ef9-b0bd-e7c68c108da2.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzU1MzA5MDksIm5iZiI6MTc3NTUzMDYwOSwicGF0aCI6Ii8yNzI4NzE0NjcvNTcyNjA1NzQyLTczNzBkNzBkLTI3MjQtNGVmOS1iMGJkLWU3YzY4YzEwOGRhMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwNDA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDQwN1QwMjU2NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ODI2N2U2YjkyODkxOGI0YjVhMDdmNTFiYTkzYzk3OWFkZjcyMTRiNGRiZTg4M2M0YjkyZDdmNjBkYTZkMjk4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.H6yyfwwWExF7foVHyDxvYdWI417f68J0n-S7_LqVmbQ">
> 
> [@chadodark-ux](https://github.com/chadodark-ux) i cant tell if this is meant to be a joke but i laughed regardless cause bro where did you even find that? anyways just in case you were actually serious, that's not even a version of this plugin, so uh maybe try downloading [this plugin](https://riolubruh.github.io/autoDownload/?file=https://raw.githubusercontent.com/riolubruh/YABDP4Nitro/main/YABDP4Nitro.plugin.js)..?

To be honest i keep getting a similar error now, 

<img width="350" height="219" alt="Image" src="https://github.com/user-attachments/assets/82aff142-eb86-4685-901d-84471a1e412e" />

**Comment by Maverynthia** [comment]
Add to FAQ: "Some stuff broke how to fix?" or text that pertains to specific error.
Answer: Remove Zeres Plugin Library (unless this is fixed)
Zalgo text needs it so it might get installed from that.
