### ISSUE TITLE
Problem with premium games error 1006

### ISSUE THREAD

**Issue by lukaa032** [riolubruh/YABDP4Nitro#77]
Error 1006 can't authenticate because ban reconize something. Games who have problem Blazing 8s Poker NIght. Check for more i didn't check everything

**Comment by riolubruh** [comment]
Not sure if this is even possible to fix but depending on how poorly the authentication is implemented it could be possible

**Comment by lukaa032** [comment]
2,3 games we can't launch problem with error 1006

**Comment by riolubruh** [comment]
82f5780c2721be0983b0ecd62611e2c93e4ccb7e
