### ISSUE TITLE
New Discord Themes

### ISSUE THREAD

**Issue by thiaguinho4** [riolubruh/YABDP4Nitro#79]
would it be possible for you to add an option to use these new themes without nitro?

![Captura de tela 2023-03-17 152232](https://user-images.githubusercontent.com/101910294/225987442-db114b37-9de1-4584-8a6f-7db105711c3d.png)

**Comment by riolubruh** [comment]
[DiscordBypasses](https://github.com/Tharki-God/BetterDiscordPlugins/blob/master/DiscordBypasses.plugin.js) has this feature!
