### ISSUE TITLE
Emoji size selector is a volume slider (and other config issues)

### ISSUE THREAD

**Issue by Weblure** [riolubruh/YABDP4Nitro#83]
The emoji size slider displays as a volume slider, and does not visually adjust:
![f33073910e64b5c150cfa1f2c3b8d9dc](https://user-images.githubusercontent.com/16730720/226526759-bd3f735c-21cf-43d4-af26-74f513ded217.gif)

However, attempting to adjust the slider does result in changes to the `emojiSize` property value.
![f9def9c80ebfcaa98afcaec17ca2ba65](https://user-images.githubusercontent.com/16730720/226527407-f5ddd379-6a3c-4e14-8dd6-6f49b6225650.gif)

These adjustments ignore the predefined steps and result in large decimal values that Discord rejects, leading to emoji images being displayed at a default size:
![0f3b9af56d821908218623c6f4f231d4](https://user-images.githubusercontent.com/16730720/226530318-b2afdc38-3b99-4d03-bb7a-5b63ca8c9f44.gif)

Reloading or adjusting the plugin after making manual changes to the config file results in the config file being reset:
![349fdce7ae570a5ad8819b8cfaedc5a0](https://user-images.githubusercontent.com/16730720/226527987-7b11a58a-f648-4130-b3b4-8c54eb8bfe3a.gif)

If the config file is set to read-only to prevent this, the plugin seems to ignore the set configuration entirely, opting to use the last known value instead.

(Note: Although I used Canary while recording the above screen captures, I have verified that these same problems persist in the latest version of stable Discord with BetterDiscord v1.8.5.)

**Comment by labs901** [comment]
same problem here
