### ISSUE TITLE
48px no longer an option?

### ISSUE THREAD

**Issue by adae22** [riolubruh/YABDP4Nitro#84]
As of 4.4.6 emotes can no longer be set to 48px (i.e. Discord's default size) via the plugin settings menu.
The plugin only accepts entries in increments of 16, 32, 64, and so on, nothing in between.

Other values can be forced via cfg file (incl. 48px).

Is this intended?

Also, after reverting back to 4.4.5 I noticed that https://github.com/riolubruh/YABDP4Nitro/issues/83#issue-1633281020 can no longer be replicated with the current version of discord and version 1.9.0 of BD. 
The slider is a regular settings slider and all changes are saved accordingly. 
![sizing](https://user-images.githubusercontent.com/95435509/227407066-03309ebd-14e2-4121-8349-ef183e14e803.PNG)
**4.4.5 does work as intended as of the time of posting this.**

Thanks for all the good work on this!

**Comment by Weblure** [comment]
The latest update now rounds your custom input number to the nearest power of 2, meaning only 8, 16, 32, 64, 128, and so on are valid numbers.

Here's a quick fix:

```
new Settings.Textbox("Size", "The size of the emoji in pixels. 64 is the default. Valid values: 16, 32, 48, 64, 80, 96, 112, 128, or powers of 2.", this.settings.emojiSize,
								value => {
									value = parseInt(value);
									if (isNaN(value)) {
										value = 64;
									} else if (value > 128) {
										value = Math.pow(2, Math.round(Math.log(value) / Math.log(2))); 
									} else if (![16, 32, 48, 64, 80, 96, 112, 128].includes(value)) {
										value = Math.min.apply(Math, [16, 32, 48, 64, 80, 96, 112, 128].filter(function(x) { return x > value }));
									}
									this.settings.emojiSize = value;
								}
							),
```
Replace lines 169-175 with the above code. Be careful not to replace any other lines or break the syntax.

**Comment by riolubruh** [comment]
> The latest update now rounds your custom input number to the nearest power of 2, meaning only 8, 16, 32, 64, 128, and so on are valid numbers.
> 
> Here's a quick fix:
> 
> ```
> new Settings.Textbox("Size", "The size of the emoji in pixels. 64 is the default. Valid values: 16, 32, 48, 64, 80, 96, 112, 128, or powers of 2.", this.settings.emojiSize,
> 								value => {
> 									value = parseInt(value);
> 									if (isNaN(value)) {
> 										value = 64;
> 									} else if (value > 128) {
> 										value = Math.pow(2, Math.round(Math.log(value) / Math.log(2))); 
> 									} else if (![16, 32, 48, 64, 80, 96, 112, 128].includes(value)) {
> 										value = Math.min.apply(Math, [16, 32, 48, 64, 80, 96, 112, 128].filter(function(x) { return x > value }));
> 									}
> 									this.settings.emojiSize = value;
> 								}
> 							),
> ```
> 
> Replace lines 169-175 with the above code. Be careful not to replace any other lines or break the syntax.
> 
> Clarification: The above is a patch for version 4.4.6 only.

Cool! I'll include this in the next patch!
