### ISSUE TITLE
Discord crashing with the plugin.

### ISSUE THREAD

**Issue by bonbonu** [riolubruh/YABDP4Nitro#85]
Yesterday 3/23/23, the plugin was working fine and when I opened discord today 3/24/23, it just said that discord had crashed. So I tried to problem-solve and reinstall discord better. Nothing worked, I took all the plugins but the nitro plugin, it just crashed better discord.
![wwww](https://user-images.githubusercontent.com/128848487/227625541-432fccb7-67c7-43bb-96f7-16bfa6573543.png)

**Comment by Pickymarker** [comment]
manually install betterdiscord using command prompt

**Comment by Weblure** [comment]
Currently exclusive to PTB and Canary, and unexclusive to this plugin (a few other plugins and libraries will also result in a crash if present in the plugin folder, disabled or not). Mostly like needs to be fixed on BD's end.
