### ISSUE TITLE
add the ability to change audio codec on mic its possible on discord because I've seen people on default better discord client have opus codec type 17 by using a plugin

### ISSUE THREAD

**Issue by Pickymarker** [riolubruh/YABDP4Nitro#87]
add the ability to change audio codec on mic its possible on discord because I've seen people on default better discord client have opus codec type 17 by using a plugin

**Comment by riolubruh** [comment]
I don't think this really relates to the plugin's theme of Nitro features, so I don't think it would make sense to add it.
