### ISSUE TITLE
Better Discord Screenshare compatibility

### ISSUE THREAD

**Issue by Pickymarker** [riolubruh/YABDP4Nitro#88]
add compatibility with this plugin so i can still use yabdp with it https://github.com/philhk/better-discord-screenshare-plugin because that has better screenshare capabilities

**Comment by riolubruh** [comment]
In the future, please refrain from making issues with really long titles (or without a title).

**Comment by riolubruh** [comment]
The plugin in question is now discontinued, so I won't be bothering to attempt to fix compatibility with it. Sorry.
