### ISSUE TITLE
Not compatible with FreeStickers

### ISSUE THREAD

**Issue by brusvv** [riolubruh/YABDP4Nitro#9]
Using the latest versions of these plugins and still see this problem.
![image](https://user-images.githubusercontent.com/55412131/175794777-7271e35b-14bf-49c4-b647-10d5bf24fb75.png)

**Comment by riolubruh** [comment]
Resolved

**Comment by brusvv** [comment]
Animated stickers are removed after sending a new message in a short period of time.

**Comment by brusvv** [comment]
> Resolved


Animated stickers are removed after sending a new message in a short period of time.
