### ISSUE TITLE
Add functionality from `better-discord-screenshare-plugin`

### ISSUE THREAD

**Issue by userMacieG** [riolubruh/YABDP4Nitro#95]
Plugin https://github.com/tinguy1/better-discord-screenshare-plugin is no longer supported, so functionality of that plugin would be nice.

**Comment by riolubruh** [comment]
Sorry, I don't quite get what you mean. Better Discord Screenshare has a fairly similar feature set to this plugin. Things that BDS have that this plugin does not are as follows:
Ability to choose video codec
Ability to choose audio codec
Ability to choose audio source
Ability to encode with a different resolution/fps than captured
A good UI
--------------------------------
Other than a good UI (which I have no idea how to do), the features that BDS provides that this plugin does not are not really that substantial.

**Comment by userMacieG** [comment]
`Ability to choose video codec` is main thing that is missing in yabd.

**Comment by riolubruh** [comment]
> `Ability to choose video codec` is main thing that is missing in yabd.

Added in 82f5780
